/*
 * MATLAB Compiler: 4.2 (R14SP2)
 * Date: Mon Oct 31 08:17:24 2005
 * Arguments: "-B" "macro_default" "-c" "-v" "-m" "-W" "main" "-T" "link:exe"
 * "-R" "-nojvm" "calcSSNR_mce.m" 
 */


#ifdef __cplusplus
extern "C" {
#endif
const unsigned char __MCC_calcSSNR_mce_public_data[] = {'3', '0', '8', '1',
                                                        '9', 'D', '3', '0',
                                                        '0', 'D', '0', '6',
                                                        '0', '9', '2', 'A',
                                                        '8', '6', '4', '8',
                                                        '8', '6', 'F', '7',
                                                        '0', 'D', '0', '1',
                                                        '0', '1', '0', '1',
                                                        '0', '5', '0', '0',
                                                        '0', '3', '8', '1',
                                                        '8', 'B', '0', '0',
                                                        '3', '0', '8', '1',
                                                        '8', '7', '0', '2',
                                                        '8', '1', '8', '1',
                                                        '0', '0', 'C', '4',
                                                        '9', 'C', 'A', 'C',
                                                        '3', '4', 'E', 'D',
                                                        '1', '3', 'A', '5',
                                                        '2', '0', '6', '5',
                                                        '8', 'F', '6', 'F',
                                                        '8', 'E', '0', '1',
                                                        '3', '8', 'C', '4',
                                                        '3', '1', '5', 'B',
                                                        '4', '3', '1', '5',
                                                        '2', '7', '7', 'E',
                                                        'D', '3', 'F', '7',
                                                        'D', 'A', 'E', '5',
                                                        '3', '0', '9', '9',
                                                        'D', 'B', '0', '8',
                                                        'E', 'E', '5', '8',
                                                        '9', 'F', '8', '0',
                                                        '4', 'D', '4', 'B',
                                                        '9', '8', '1', '3',
                                                        '2', '6', 'A', '5',
                                                        '2', 'C', 'C', 'E',
                                                        '4', '3', '8', '2',
                                                        'E', '9', 'F', '2',
                                                        'B', '4', 'D', '0',
                                                        '8', '5', 'E', 'B',
                                                        '9', '5', '0', 'C',
                                                        '7', 'A', 'B', '1',
                                                        '2', 'E', 'D', 'E',
                                                        '2', 'D', '4', '1',
                                                        '2', '9', '7', '8',
                                                        '2', '0', 'E', '6',
                                                        '3', '7', '7', 'A',
                                                        '5', 'F', 'E', 'B',
                                                        '5', '6', '8', '9',
                                                        'D', '4', 'E', '6',
                                                        '0', '3', '2', 'F',
                                                        '6', '0', 'C', '4',
                                                        '3', '0', '7', '4',
                                                        'A', '0', '4', 'C',
                                                        '2', '6', 'A', 'B',
                                                        '7', '2', 'F', '5',
                                                        '4', 'B', '5', '1',
                                                        'B', 'B', '4', '6',
                                                        '0', '5', '7', '8',
                                                        '7', '8', '5', 'B',
                                                        '1', '9', '9', '0',
                                                        '1', '4', '3', '1',
                                                        '4', 'A', '6', '5',
                                                        'F', '0', '9', '0',
                                                        'B', '6', '1', 'F',
                                                        'C', '2', '0', '1',
                                                        '6', '9', '4', '5',
                                                        '3', 'B', '5', '8',
                                                        'F', 'C', '8', 'B',
                                                        'A', '4', '3', 'E',
                                                        '6', '7', '7', '6',
                                                        'E', 'B', '7', 'E',
                                                        'C', 'D', '3', '1',
                                                        '7', '8', 'B', '5',
                                                        '6', 'A', 'B', '0',
                                                        'F', 'A', '0', '6',
                                                        'D', 'D', '6', '4',
                                                        '9', '6', '7', 'C',
                                                        'B', '1', '4', '9',
                                                        'E', '5', '0', '2',
                                                        '0', '1', '1', '1'
                                                        , '\0'};

const char *__MCC_calcSSNR_mce_name_data = "calcSSNR_mce";

const char *__MCC_calcSSNR_mce_root_data = "";

const unsigned char __MCC_calcSSNR_mce_session_data[] = {'3', '3', '5', '9',
                                                         '2', '6', '7', '4',
                                                         '3', '9', 'C', '1',
                                                         'D', '6', 'B', 'C',
                                                         'B', 'B', '9', 'C',
                                                         'D', '4', '9', '7',
                                                         '7', 'A', '6', '6',
                                                         '6', '1', 'C', '9',
                                                         'F', '6', 'F', '2',
                                                         '9', '5', 'E', '6',
                                                         '3', '6', '2', 'D',
                                                         '5', '3', 'C', 'C',
                                                         '2', 'A', 'B', '0',
                                                         '3', 'D', 'A', '8',
                                                         'E', '9', 'D', 'A',
                                                         '2', '9', '0', '6',
                                                         '3', 'E', '1', 'D',
                                                         'B', '7', '5', '7',
                                                         'C', '1', '6', '0',
                                                         '6', 'A', '8', 'F',
                                                         '9', '7', 'A', '6',
                                                         '2', '6', '8', 'A',
                                                         'E', '6', '8', '4',
                                                         'B', '6', 'D', '3',
                                                         '1', 'E', 'B', '9',
                                                         '9', '9', 'E', '3',
                                                         'C', '5', '6', 'E',
                                                         '4', 'C', '8', 'F',
                                                         '0', '2', 'F', '4',
                                                         '4', 'D', 'C', '3',
                                                         '5', '2', '3', 'D',
                                                         '3', 'D', '6', '9',
                                                         'F', '2', '6', 'A',
                                                         '6', '7', 'D', '9',
                                                         'E', 'B', 'E', '4',
                                                         '5', '5', 'E', 'A',
                                                         '3', 'D', 'F', '6',
                                                         '1', '9', '5', '3',
                                                         '2', '3', '5', '7',
                                                         'F', '5', 'C', '3',
                                                         'E', '7', 'E', '6',
                                                         '4', '2', '0', 'E',
                                                         '4', '6', 'A', '5',
                                                         '2', 'C', '5', '3',
                                                         'E', '7', '8', 'D',
                                                         '2', '9', 'F', '9',
                                                         'F', 'F', 'F', '0',
                                                         '1', 'A', '6', 'E',
                                                         'B', 'B', '8', '5',
                                                         'A', 'B', '8', 'F',
                                                         '7', '5', '0', '7',
                                                         'E', 'A', '4', '4',
                                                         '9', 'D', 'D', '8',
                                                         '4', 'E', '5', 'E',
                                                         '8', '6', 'F', 'B',
                                                         '7', '1', 'A', 'F',
                                                         '8', 'D', '4', '1',
                                                         'E', 'C', 'B', '1',
                                                         '2', '3', 'E', 'D',
                                                         '2', 'E', 'D', '2',
                                                         '8', '2', '6', '4',
                                                         '7', '3', '5', '7',
                                                         'E', '3', '1', '9',
                                                         'A', '3', '6', 'C'
                                                         , '\0'};

const char *__MCC_calcSSNR_mce_matlabpath_data[] = {"calcSSNR_mce/",
                                                    "toolbox/compiler/deploy/",
                                                    "home/rickg/matlab/",
                                                    "home/rickg/Src/Matlab/Std/Geometry/",
                                                    "home/rickg/Src/Matlab/Std/Utils/",
                                                    "home/rickg/Src/Matlab/VolumeAveraging/",
                                                    "home/rickg/Src/Matlab/Interpolation/",
                                                    "home/rickg/Src/Matlab/MatTomo/",
                                                    "home/rickg/Src/Matlab/MatTomo/Utils/",
                                                    "$TOOLBOXMATLABDIR/general/",
                                                    "$TOOLBOXMATLABDIR/ops/",
                                                    "$TOOLBOXMATLABDIR/lang/",
                                                    "$TOOLBOXMATLABDIR/elmat/",
                                                    "$TOOLBOXMATLABDIR/elfun/",
                                                    "$TOOLBOXMATLABDIR/specfun/",
                                                    "$TOOLBOXMATLABDIR/matfun/",
                                                    "$TOOLBOXMATLABDIR/datafun/",
                                                    "$TOOLBOXMATLABDIR/polyfun/",
                                                    "$TOOLBOXMATLABDIR/funfun/",
                                                    "$TOOLBOXMATLABDIR/sparfun/",
                                                    "$TOOLBOXMATLABDIR/scribe/",
                                                    "$TOOLBOXMATLABDIR/graph2d/",
                                                    "$TOOLBOXMATLABDIR/graph3d/",
                                                    "$TOOLBOXMATLABDIR/specgraph/",
                                                    "$TOOLBOXMATLABDIR/graphics/",
                                                    "$TOOLBOXMATLABDIR/uitools/",
                                                    "$TOOLBOXMATLABDIR/strfun/",
                                                    "$TOOLBOXMATLABDIR/imagesci/",
                                                    "$TOOLBOXMATLABDIR/iofun/",
                                                    "$TOOLBOXMATLABDIR/audiovideo/",
                                                    "$TOOLBOXMATLABDIR/timefun/",
                                                    "$TOOLBOXMATLABDIR/datatypes/",
                                                    "$TOOLBOXMATLABDIR/verctrl/",
                                                    "$TOOLBOXMATLABDIR/codetools/",
                                                    "$TOOLBOXMATLABDIR/helptools/",
                                                    "$TOOLBOXMATLABDIR/demos/",
                                                    "toolbox/local/",
                                                    "toolbox/compiler/",
                                                    "toolbox/images/images/",
                                                    "toolbox/images/imuitools/",
                                                    "toolbox/optim/",
                                                    "toolbox/signal/signal/",
                                                    "home/rickg/TOM/IOfun/",
                                                    "home/rickg/TOM/Sptrans/"};
const int __MCC_calcSSNR_mce_matlabpath_data_count = 44;

const char *__MCC_calcSSNR_mce_classpath_data[] = { "" };
const int __MCC_calcSSNR_mce_classpath_data_count = 0;

const char *__MCC_calcSSNR_mce_lib_path_data[] = { "" };
const int __MCC_calcSSNR_mce_lib_path_data_count = 0;

const char *__MCC_calcSSNR_mce_mcr_application_options[] = {"-nojvm"};
const int __MCC_calcSSNR_mce_mcr_application_option_count = 1;
const char *__MCC_calcSSNR_mce_mcr_runtime_options[] = { "" };
const int __MCC_calcSSNR_mce_mcr_runtime_option_count = 0;
#ifdef __cplusplus
}
#endif


