%PMIPath        Add the necessary PMI directories to the MATLAB path.
%
%   pmipath
%
%   Make sure to set the BasePath variable in this function to the base path at
%   your site.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  $Author: rickg $
%
%  $Date: 2004/01/03 08:25:50 $
%
%  $Revision: 1.1.1.1 $
%
%  $Log: pmipath.m,v $
%  Revision 1.1.1.1  2004/01/03 08:25:50  rickg
%  Matlab Source
%
%  Revision 3.0  1999/06/17 19:29:38  rjg
%  Initial Revision for PMI 3.0
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function pmipath

%%
%%  PMI directories
%%
if strcmp(computer, 'PCWIN')
    BasePath = 'D:\Src\Matlab\PMI';
    PMIPath = [ ...
            BasePath ';' ...
            BasePath '\Forward;' ...
            BasePath '\Reconstruct;' ...
            BasePath '\Reconstruct\PerfMeas;' ...
            BasePath '\Visualize;' ...
            BasePath '\UI;' ...
            BasePath '\Util;' ...
            BasePath '\Contrib;' ...
            BasePath '\Development' ];
else
    BasePath = '/d/Src/Matlab/PMI';
    PMIPath = [ ...
            BasePath ':' ...
            BasePath '/Forward:' ...
            BasePath '/Reconstruct:' ...
            BasePath '/Reconstruct/PerfMeas:' ...
            BasePath '/Visualize:' ...
            BasePath '/UI:' ...
            BasePath '/Util:' ...
            BasePath '/Contrib:' ...
            BasePath '/Development' ];
end
            
path(path, PMIPath);
