%Hot Clutter Processing And Simulation Library.
%
% Simulation
%    bist_rcs   - Compute the required bistatic RCS to exceed the noise floor.
%    bist_sll   - Compute the required bistatic RCS to exceed the antenna SLL.
%    pndop      - Generate a doppler shifted PN sequence.
%    shad_map   - Generate a shadow map from a DMA elevation map & a viewpoint.
%    shad_plt   - Plot a shadow map generated by shad_map.
%    srpngen    - Generate a ML shift register pseudo-random sequence.
%
% Signal & Data Processing
%    air_proc   - Generate RD maps and sigma0 info from raw aircraft HC Data.
%    air_sig0   - Compute sigma0 from aircraft range-doppler information.
%    airgamma   - Compute gamma from sigma0 and positional info for aircraft.
%    azrmap     - Generate a colormap using range and azimuth as indep. vars.
%    bi_range   - Compute bistatic range parameters R1, R2 and angle from delta
%                 range and Tx position.
%    bi_res2    - Compute bistatic resolution cell area given ranges to cell,
%                 Tx position, azimuth beamwidth and bandwidth.
%    biarintf   - Bistatic area integration function (utility).
%    bigcpi     - Convert 4 RSTER CPIs to a single range-pulse CPI.
%    bist_res   - Compute bistatic resolution cell area given bandwidth,
%                 beamwidth, Tx position and sampling matrix.
%    ch_pdgrm   - Compute a periodogram for each channel.
%    corrping   - Correct for local oscillator ping-pong.
%    cpicint    - Coherently integrate a range-pulse CPI.
%    frqavgs0   - Plot average sigma0 for 4 frequencies used in HC ground test.
%    gen_time   - Generate a time index for a range-pulse CPI.
%    genhcmf    - Generate frequency domain HC  matched filters (PCW, PN).
%    getphase   - Compute offset frequency and STD of a range-pulse CPI.
%    hcazpatt   - Generate a range descriminated azimuth pattern using HC data.
%    hcdet      - Threshold detect a matrix independently for each element.
%    hcg_chk    - Compare sigma0 values computed by two methods.
%    hcg_proc   - Perform hot clutter signal processing on a data set.
%    hcg_s0     - Process a ground hot clutter measurement seqeuence.
%    hcg_vald   - Report on data produced by hcg_s0.
%    hcproc     - Process a hot clutter CPI (old version).
%    hcrngdop   - Compute a range-doppler from a CPIrp.
%    lear_ant   - Lear jet antenna azimuth pattern model (interpolated data).
%    lfrank     - Little Frank azimuth pattern model (mathematical).
%    lfrank2    - Little Frank azimuth pattern model (interpolated data).
%    ltlfrk_el  - Little Frank elevation pattern model (interpolated data).
%    mfreqpow   - Compute and plot multi-frequency power levels.
%    mfsigma0   - Compute mean sigma0 from multi-frequency data.
%    mkmfcoeff  - Generate real-time matched filter coefficients.
%    proc_files - Process all of the files from a particular ground measurment.
%    proc_noise - Process an ACAL noise file in the same manner as HC data.
%    proc_rdmaps - Process range-doppler maps from an aircraft measurement seq.
%    s02gamma   - Generate gamma from sigma0 for ground HC measurements.
%    sigma0dp   - Derive sigma0 from signal processor output and direct path 
%                 power level.
%    sigma0pt   - Derive sigma0 from signal processor output and measured Tx
%                 power level.
%    sub13      - 13 element average and subsampling.
%
% DMA Elevation Map Tools
%    dmazoom    - Zoom in on a DMA map with contour, mesh or surface plotting.
%    submap     - Select a portion of a DMA map.
