%    This script is designed to process all of the files for a given
%  sweep of 13 uSec pulsed Hot Clutter data collection.

%%
%%    Vector of file names to loop through.
%%
Base = 'r19812';
FileNum = [ 24:56 58:60 18 61 ];
FileNum = [ 28 36];

%%
%%    System constants
%%    
TxPos  = -57330+j*34040;
Delta = [0:1650]' * 1e-6 * 3e8;
W = svrster(13, 0, 435 /450, 3, 60);

%%
%%    Pulsed CW matched filter coefficients.
%%
MFC013 = conj(fft(ones(13,1), 1651));

%%
%%    These values were generated by looking at the data files manually.
%%
DirPathdB = 146.1;
NoisedB = 46;    % measured value from shadowed areas on several plots
FreqOffset = 3.48795355731;
tCPI = gen_time(1701, 64, 3302) * 1e-6;
PhaseCorr = exp(-j * 2 * pi * FreqOffset * tCPI);

orient('landscape');

%%
%%    Loop over each file.
%%
index = 1;
for currfile = FileNum

    %%
    %%    Load required raw data file.
    %%
    filename = [Base num2str(currfile) 'v1'];
    disp(['Loading : ' filename]);
    eval(['load ' filename]);

    %%
    %%    Compute azimuth.
    %%
    Azimuth(index) = mean(azxmit);

    %%
    %%    Perform beamforming, doppler correction, coherent integration,
    %%  matched filtering and aligning of direct path response to zero.
    %%
    disp('Processing...')
    proc13

    %%
    %%    Extract peak information from processing, put in vector to plot
    %%  against file number.
    %%
    vDPPeak(index) = DipolePeak;
    vDPPeakIdx(index) = DipolePeakIdx;
    vMFOutPeak(index) = mfout(1);

    %%
    %%    Threshhold matched filter output @ 10 dB above the noise floor.
    %%
    MfoutAz(:,index) = mfout;

%    idx = find(10*log10(real(mfout .* conj(mfout))) < NoisedB + 10);
%    mfout(idx) = ones(size(idx)) .*  NaN;

    %%
    %%    Compute sigma0, noise floor and range from RSTER
    %%
    [Sigma0 NoiseFlr Range] = ...
        sigma0(mfout, Delta, Azimuth(index), TxPos, DirPathdB, NoisedB);
    matSigma0(:,index) = Sigma0;
    matNoiseFlr(:,index) = NoiseFlr;
    matRange(:,index) = Range;


    %%
    %%    Plot sigma0 and noise floor wrt range from RSTER.
    %%
    disp('Plotting...')
    plot(Range / 1000 * .5399568, 10 * log10(abs(Sigma0)), ...
        Range / 1000 * .5399568, 10 * log10(abs(NoiseFlr)), '--r');
    hold on
    axis([0 100 -100 -20])
    grid
    xlabel('Range (NMi)')
    ylabel('Sigma0 (dB)')
    title([ filename '  13 uSec PCW AZ = ' num2str(Azimuth(index))])
    plot([72 78], [-26 -26], '-y');
    text(81, -26.5, 'Sigma0');
    plot([72 78], [-34 -34], '--r');
    text(81, -34.5, 'Noise Floor');
    hold off
%    print

    %%
    %%    Save current workspace variables to disk.
    %%
%    eval(['save s0' num2str(currfile)]);
    index = index + 1;
end

%save PeakValues  vDPPeak vDPPeakIdx vMFOutPeak
%save S0RangeCutsNaN
