%SHAD_PLT           Plot a shadow plot generated by shad_map.
%
%    shad_plt(xdist, ydist, Vis, ObsPos, SubSample)
%
%    xdist      East-west distance from origin of each column [kilometers].
%
%    ydist      North-south distance from origin of each row [kilometers].
%
%    Vis        Visibility array
%
%    ObsPos     Observation point(s) relative to origin [kilometers, complex].
%
%    SubSample  OPTIONAL: Sub sampling factor for plotting of visibility array
%               (default: 1).
%
%	    SHAD_PLT displays a shadow map of area specified by xdist and ydist
%    and defined by Vis a binary (0's and 1's) specifying line-of-site 
%    visibility from ObsPos.
%
%
%    Calls: none
%
%    Bugs: does not take into account sperical earth.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  $Author: rickg $
%
%  $Date: 2004/01/03 08:24:32 $
%
%  $Revision: 1.1.1.1 $
%
%  $Log: shad_plt.m,v $
%  Revision 1.1.1.1  2004/01/03 08:24:32  rickg
%  Matlab Source
%
%  
%     Rev 1.1   27 Oct 1993 10:32:06   rjg
%  Plots multiple observation points, SubSample is now optional and defaults to
%  one.
%  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function shad_plt(xdist, ydist, Vis, ObsPos, SubSample)

if nargin < 5,
    SubSample = 1;
end

%%
%%    Size of the grid
%%
nXgrid = length(xdist);
nYgrid = length(ydist);

%%
%%    Get points to be plotted
%%
xval = xdist(1:SubSample:nXgrid);
yval = ydist(1:SubSample:nYgrid);

%%
%%    Find the points that are shadowed
%%
ShadMap = ~Vis(1:SubSample:nYgrid, 1:SubSample:nXgrid);
[iShad jShad] = find(ShadMap);

%%
%%    Mark the shadowed points
%%
plot(xval(jShad), yval(iShad), '.w');

%%
%%    Display the obeservation point(s)
%%
plot(ObsPos, '*r');
