tplot(20*log10(abs(cpi1(1:wrecord,2))),  ...
'Simulated Receiver Noise', ...
'RSTER Azimuth: 302', ...
'Channel 2 (Row data)', ...
['Mean Power: ' ...
num2str(10*log10(mean(real(cpi1(:,2) .* conj(cpi1(:,2)))))) ' dB'], ...
'File: RandomBigCPI')
title('Simulated Noise std: 254');
xlabel('Time (uSecs)')
ylabel('Amplitude (dB)')


