%%
%%    Integrated Beamformer Output
%%
tplot(20*log10(abs(bfcpi_ci)),  ...
'Receiver Noise.', ...
'RSTER Azimuth: 302', ...
'Beamformer Output', ...
'64 Pulse Integration', ...
['Mean Power: ' ...
num2str(10 * log10(mean(real(bfcpi_ci .* conj(bfcpi_ci))))) ' dB'], ...
'66.7km @ 302 degrees', ...
'File: acal101v1')
title('M Mountain')
xlabel('Time (uSecs)')
ylabel('Amplitude (dB)')
disp('Change axis ?')
grid
keyboard
print

%%
%%    Match filtered dipole
%%
tplot(20*log10(abs(mfout)),  ...
'Receiver Noise.', ...
'RSTER Azimuth: 302', ...
'Beamformer Output', ...
'64 Pulse Integration', ...
'Matched Filter Output', ...
['Mean Power: ' ...
num2str(10 * log10(mean(real(mfout .* conj(mfout))))) ' dB'], ...
'66.7km @ 302 degrees', ...
'File: acal101v1')
title('M Mountain')
xlabel('Time (uSecs)')
ylabel('Amplitude (dB)')
disp('Change axis ?')
grid
keyboard
print