#!/bin/sh
#
#  volavg startup script

source ${PARTICLE_DIR}/particle.cfg

unset DISPLAY

echo -n "Starting volavg_mce ..."
nice -n ${PARTICLE_NICE} volavg_mce $@ >${1}.log 2>&1 &
echo "started as a background process."
