
#ifndef PPPGRAPHVIEW_H
#define PPPGRAPHVIEW_H

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif 

// include files for Qt
#include <qwidget.h>

class PPPGraphDoc;

/** The PPPGraphView class provides the view widget for the PPPGraphApp instance.	
	* The View instance inherits QWidget as a base class and represents the view object of a KTMainWindow. As PPPGraphView is part of the
	* docuement-view model, it needs a reference to the document object connected with it by the PPPGraphApp class to manipulate and display
	* the document structure provided by the PPPGraphDoc class.
 	* 	
 	* @author Source Framework Automatically Generated by KDevelop, (c) The KDevelop Team.
	* @version KDevelop version 0.4 code generation
 	*/
class PPPGraphView : public QWidget
{
  Q_OBJECT

public:
  /** Constructor for the main view */
  PPPGraphView(QWidget* parent = 0, const char* name=0);
  /** Destructor for the main view */
  ~PPPGraphView();

	/** returns a pointer to the document connected to the view instance. Mind that this method requires a PPPGraphApp instance as a parent
		* widget to get to the window document pointer by calling the PPPGraphApp::getDocument() method.
		*
		* @see PPPGraphApp#getDocument
		*/
	PPPGraphDoc* getDocument() const;
	
  /** contains the implementation for printing functionality */
	void print(QPrinter* m_pPrinter);
	
		
private:
	
};

#endif // PPPGRAPHVIEW_H













