load forwardAll.txt
load forwardOperator.txt
load forward_pointCapture.txt
load model.txt
load model_corrected.txt
load model_pointCapture.txt
load rhs.txt
load rhs_pointCapture.txt
load validBottomSwapped_closeNeighbors.txt
load validBottomSwapped_culled.txt
load validBottomSwapped_pointCapture.txt
load validBottom_closeNeighbors.txt
load validBottom_culled.txt
load validBottom_pointCapture.txt
load validTopSwapped_closeNeighbors.txt
load validTopSwapped_culled.txt
load validTopSwapped_pointCapture.txt
load validTop_closeNeighbors.txt
load validTop_culled.txt
load validTop_pointCapture.txt
load zBottom_final.txt
load zBottom_swapped.txt
load zPredict.txt
load zPredict_corrected.txt
load zTop_final.txt
load zTop_swapped.txt
load zBottom_initial.txt
load zTop_initial.txt
