%UI_ANOMALY
function [UIHandles, YEnd] = ui_anomaly(hFig, UIHandles, XStart, szXFrame, YStart, szYEdit)

stYEdit = YStart - szYEdit ;
stYLabel = stYEdit - 2;
szYFrame = 6 * szYEdit + 6;
stYFrame = stYEdit - szYFrame;
YEnd = stYFrame;

%%
%%  Anomalies
%%
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[XStart stYFrame+szYFrame-5 szXFrame szYEdit], ...
    'String', 'Absorption Anomaly(s)', ...
    'Style','text');

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[XStart stYFrame szXFrame szYFrame], ...
    'Style','frame');

%%
%%  Spherical object(s) function
%%
stXLabel1 = XStart + 2;
szXLabel1 = 35;
stXEdit1 = stXLabel1 + szXLabel1 + 1;
szXEdit1 = 100;
stXLabel2 = stXEdit1 + szXEdit1 + 2;
szXLabel2 = 28;
stXEdit2 = stXLabel2 + szXLabel2 + 1;
szXEdit2 = 49;
stXLabel3 = stXEdit2 + szXEdit2 + 2;

stYEdit = stYFrame + szYFrame - szYEdit;
stYLabel = stYEdit - 2;

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','left', ...
    'String','Sphere', ...
    'Style','text');

stYEdit = stYEdit - szYEdit;
stYLabel = stYEdit - 2;
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','center(s):', ...
    'Style','text');

UIHandles.SphereCtr = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'Style','edit');

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','radius:', ...
    'Style','text');

UIHandles.SphereRad = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit2 stYEdit szXEdit2 szYEdit], ...
    'Style','edit');

stYEdit = stYEdit - szYEdit;
stYLabel = stYEdit - 2;
szXLabel1 = 35;
stXEdit1 = stXLabel1 + szXLabel1 + 1;
szXEdit1 = 100;

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','del mu_a:', ...
    'Style','text');

UIHandles.SphereDelta = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'Style','edit');

%%
%%  Block object function
%%
stYEdit = stYEdit - 2 - szYEdit;
stYLabel = stYEdit - 2;
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','left', ...
    'String','Block', ...
    'Style','text');

stYEdit = stYEdit - szYEdit;
stYLabel = stYEdit - 2;
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','center(s):', ...
    'Style','text');

UIHandles.BlockCtr = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'Style','edit');

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','lengths:', ...
    'Style','text');

UIHandles.BlockDims = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit2 stYEdit szXEdit2 szYEdit], ...
    'Style','edit');

stYEdit = stYEdit - szYEdit;
stYLabel = stYEdit - 2;
szXLabel1 = 35;
stXEdit1 = stXLabel1 + szXLabel1 + 1;
szXEdit1 = 100;

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','del mu_a:', ...
    'Style','text');

UIHandles.BlockDelta = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'Style','edit');
