%UI_FWDMED
function [UIHandles, YEnd] = ui_fwdmed(hFig, UIHandles, XStart, szXFrame, YStart, szYEdit)

szYFrame = 4 * szYEdit + 12;
stYFrame = YStart - szYFrame - szYEdit;
stYEdit = YStart - szYEdit;
YEnd = stYFrame;

%%
%%  Forward Problem Medium parameters
%%
hc = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[XStart stYFrame+szYFrame-5 szXFrame szYEdit], ...
    'String','Forward Solution Medium Parameters', ...
    'Style','text');

UIHandles.vTAB1 = [UIHandles.vTAB1 hc];

hc = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[XStart stYFrame szXFrame szYFrame], ...
    'Style','frame');

UIHandles.vTAB1 = [UIHandles.vTAB1 hc];
stXLabel1 = XStart + 2;
szXLabel1 = 30;
szXEdit = 100;
stXEdit1 = stXLabel1 + szXLabel1 + 1;
stXLabel2 = stXEdit1 + szXEdit + 1;
szXLabel2 = szXFrame - szXLabel1 - szXEdit - 6;

stYEdit = stYFrame + szYFrame - szYEdit - 2;
stYLabel = stYEdit - 2;

%%
%%  Index of refraction
%%
hc = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','n:', ...
    'Style','text');
UIHandles.vTAB1 = [UIHandles.vTAB1 hc];

hc = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'HorizontalAlignment','right', ...
    'Style','edit');
UIHandles.Fwd_idxRefr = hc;

UIHandles.vTAB1 = [UIHandles.vTAB1 hc];
hc = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','index of refraction', ...
    'Style','text');
UIHandles.vTAB1 = [UIHandles.vTAB1 hc];

%%
%%  Scattering mean cosine angle
%%
stYEdit = stYEdit - szYEdit - 2;
stYLabel = stYEdit - 2;
hc = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','g:', ...
    'Style','text');
UIHandles.vTAB1 = [UIHandles.vTAB1 hc];

hc = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'Style','edit');
UIHandles.Fwd_g = hc;
UIHandles.vTAB1 = [UIHandles.vTAB1 hc];

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','mean cos angle', ...
    'Style','text');
UIHandles.vTAB1 = [UIHandles.vTAB1 hc];

%%
%%  Scattering coefficient
%%
stYEdit = stYEdit - szYEdit - 2;
stYLabel = stYEdit - 2;
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','mu_s:', ...
    'Style','text');
UIHandles.Fwd_Mu_s = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'Style','edit');
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','cm^-1', ...
    'Style','text');


%%
%%  Absorption coefficient
%%
stYEdit = stYEdit - szYEdit - 2;
stYLabel = stYEdit - 2;
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','mu_a:', ...
    'Style','text');
UIHandles.Fwd_Mu_a = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'Style','edit');
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','cm^-1', ...
    'Style','text');


