%UI_FWDSRCDET
function [UIHandles, YEnd] = ui_fwdsrcdet(hFig, UIHandles, XStart, szXFrame, YStart, szYEdit)

%%
%%  Source & Detector Data
%%
stYEdit = YStart - szYEdit ;
stYLabel = stYEdit - 2;
szYFrame = 14 * szYEdit + 27;
stYFrame = stYEdit - szYFrame;
YEnd = stYFrame;

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[XStart stYFrame+szYFrame-5 szXFrame szYEdit], ...
    'String','Forward Solution Source & Detector Data', ...
    'Style','text');

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[XStart stYFrame szXFrame szYFrame], ...
    'Style','frame');

stXLabel1 = XStart + 2;
szXLabel1 = 55;
szXEdit = 120;
stXEdit1 = stXLabel1 + szXLabel1 + 1;
stXLabel2 = stXEdit1 + szXEdit + 2;
szXLabel2 = 30;

stYEdit = stYFrame + szYFrame - 4 - szYEdit;
stYLabel = stYEdit - 2;

%%
%%  Source X positions
%%
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','Source Pos. X:', ...
    'Style','text');
UIHandles.Fwd_SrcXPos = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'HorizontalAlignment','right', ...
    'Style','edit');
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'HorizontalAlignment','left', ...
    'String','cm', ...
    'Style','text');

%%
%%  Source Y positions
%%
stYEdit = stYEdit - 2 - szYEdit;
stYLabel = stYEdit - 2;
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','Y:', ...
    'Style','text');
UIHandles.Fwd_SrcYPos = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'HorizontalAlignment','right', ...
    'Style','edit');

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'HorizontalAlignment','left', ...
    'String','cm', ...
    'Style','text');

%%
%%  Source Z positions
%%
stYEdit = stYEdit - 2 - szYEdit;
stYLabel = stYEdit - 2;
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','Z:', ...
    'Style','text');
UIHandles.Fwd_SrcZPos = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'HorizontalAlignment','right', ...
    'Style','edit');

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'HorizontalAlignment','left', ...
    'String','cm', ...
    'Style','text');

%%
%%  Source Amplitudes
%%
szXEditAmp = 60;
stXLabelAmp = stXEdit1 + szXEditAmp + 1;
szXLabelAmp = 100;
stYEdit = stYEdit - 2 - szYEdit;
stYLabel = stYEdit - 2;
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','Amplitude:', ...
    'Style','text');
UIHandles.Fwd_SrcAmp = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEditAmp szYEdit], ...
    'HorizontalAlignment','right', ...
    'Style','edit');
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabelAmp stYLabel szXLabelAmp szYEdit], ...
    'HorizontalAlignment','left', ...
    'String','dB, per source plane', ...
    'Style','text');

%%
%%  Detector X positions
%%
stYEdit = stYEdit - 6 - szYEdit;
stYLabel = stYEdit - 2;
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','Det. Pos. X:', ...
    'Style','text');
UIHandles.Fwd_DetXPos = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'HorizontalAlignment','right', ...
    'Style','edit');
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'HorizontalAlignment','left', ...
    'String','cm', ...
    'Style','text');

%%
%%  Detector Y positions
%%
stYEdit = stYEdit - 2 - szYEdit;
stYLabel = stYEdit - 2;
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','Y:', ...
    'Style','text');
UIHandles.Fwd_DetYPos = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'HorizontalAlignment','right', ...
    'Style','edit');
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'HorizontalAlignment','left', ...
    'String','cm', ...
    'Style','text');

%%
%%  Detector Z positions
%%
stYEdit = stYEdit - 2 - szYEdit;
stYLabel = stYEdit - 2;
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','Z:', ...
    'Style','text');
UIHandles.Fwd_DetZPos = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'HorizontalAlignment','right', ...
    'Style','edit');
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'HorizontalAlignment','left', ...
    'String','cm', ...
    'Style','text');

%%
%%  Sensor position error
%%
stYEdit = stYEdit - 6 - szYEdit;
stYLabel = stYEdit - 2;
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','Position Error:', ...
    'Style','text');
UIHandles.Fwd_SensorError = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[0.65 0.65 0.65], ...
    'enable', 'off',...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'Style','edit');
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','cm std.', ...
    'Style','text');


stYEdit = stYEdit - 4 - szYEdit;
stYLabel = stYEdit - 2;
 uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','Mod. Freq.(s):', ...
    'Style','text');

UIHandles.Fwd_ModFreq = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'Style','edit');
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','MHz', ...
    'Style','text');

%%
%%  Noise level controls
%%
szXLabel1 = 70;
stXEdit1 = stXLabel1 + szXLabel1 + 1;
szXEdit1 = 25;
stXLabel2 = stXEdit1 + szXEdit1 + 1;
szXLabel2 = 120;
stYEdit = stYEdit - 6 - szYEdit;
stYLabel = stYEdit - 2;
UIHandles.SrcSNRflag = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit szXLabel1 szYEdit], ...
    'String','Source SNR:', ...
    'Style','checkbox');
UIHandles.SrcSNR = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'Style','edit');
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','dB per det. rel. to total fluence', ...
    'Style','text');

stYEdit = stYEdit - 1 - szYEdit;
stYLabel = stYEdit - 2;
UIHandles.DetSNRflag = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit szXLabel1 szYEdit], ...
    'String','Detector SNR:', ...
    'Style','checkbox');
UIHandles.DetSNR = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'Style','edit');
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','dB relative to peak total fluence', ...
    'Style','text');

stYEdit = stYEdit - 1 - szYEdit;
stYLabel = stYEdit - 2;
UIHandles.ScatSNRflag = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit szXLabel1 szYEdit], ...
    'String','Scattered SNR:', ...
    'Style','checkbox');
UIHandles.ScatSNR = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'Style','edit');
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','dB realtive to peak scat. fluence', ...
    'Style','text');

stYEdit = stYEdit - 1 - szYEdit;
stYLabel = stYEdit - 2;
UIHandles.VecNormSNRflag = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit szXLabel1 szYEdit], ...
    'String','Vec. norm SNR:', ...
    'Style','checkbox');
UIHandles.VecNormSNR = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'Style','edit');
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','dB rel. to scat. vector norm', ...
    'Style','text');
