%UI_INVMOD
function [UIHandles, YEnd] = ui_invmod(hFig, UIHandles, XStart, szXFrame, YStart, szYEdit)

szYFrame = 5 * szYEdit + 15;
stYFrame = YStart - szYFrame - szYEdit;
stYEdit = YStart - szYEdit;
YEnd = stYFrame;

%%
%%  Inverse Problem Model
%%

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[XStart stYFrame+szYFrame-5 szXFrame szYEdit], ...
    'String','Inverse Problem Model', ...
    'Style','text');

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[XStart stYFrame szXFrame szYFrame], ...
    'Style','frame');

stXLabel1 = XStart + 2;
szXLabel1 = szXFrame / 2 - 3;
stXLabel2 = stXLabel1 + szXLabel1 + 2;
szXLabel2 = szXLabel1;
stYEdit = stYFrame + szYFrame - 2 - szYEdit;
UIHandles.Inv_Born = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit szXLabel1 szYEdit], ...
    'callback', 'rbInvMethod(''Born'')', ...
    'String','Born-1', ...
    'Style','radiobutton');


UIHandles.Inv_Rytov = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel2 stYEdit szXLabel2 szYEdit], ...
    'callback', 'rbInvMethod(''Rytov'')', ...
    'String','Rytov-1', ...
    'Enable', 'off', ...
    'Style','radiobutton');

%%
%%  Inverse problem boundary condition implementation
%%
stYEdit = stYEdit - szYEdit;
stYLabel = stYEdit - 2;
UIHandles.Inv_ExtrapBnd = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit szXLabel1 szYEdit], ...
    'callback', 'rbInvBoundary(''Extrapolated'')', ...
    'String','Extrapolated Boundary', ...
    'Style','radiobutton');

UIHandles.Inv_InfMedium = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel2 stYEdit szXLabel2 szYEdit], ...
    'callback', 'rbInvBoundary(''Infinite'')', ...
    'String','Infinite Medium', ...
    'Style','radiobutton');

%%
%%  Inverse problem computation volume
%%
stYEdit =  stYEdit - 5 - szYEdit;
stYLabel = stYEdit - 2;

szXEdit = 40;
szXLabel1 = 24;
stXEdit1 = stXLabel1 +szXLabel1+1;

szXLabel2 = 20;
stXLabel2 = stXEdit1 + szXEdit + 2;
stXEdit2 = stXLabel2 + szXLabel2 + 1;

szXLabel3 = 20;
stXLabel3 = stXEdit2 + szXEdit + 2;
stXEdit3 = stXLabel3 + szXLabel3 + 1;

szXLabel4 = 10;
stXLabel4 = stXEdit3 + szXEdit + 3;

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','X min:', ...
    'Style','text');
UIHandles.Inv_XMin = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'Style','edit');

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','max:', ...
    'Style','text');
UIHandles.Inv_XMax = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit2 stYEdit szXEdit szYEdit], ...
    'Style','edit');

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel3 stYLabel szXLabel3 szYEdit], ...
    'String','step:', ...
    'Style','text');
UIHandles.Inv_XStep = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit3 stYEdit szXEdit szYEdit], ...
    'Style','edit');

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel4 stYLabel szXLabel4 szYEdit], ...
    'String','cm', ...
    'Style','text');

stYEdit =  stYEdit - 2 - szYEdit;
stYLabel = stYEdit - 2;

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','Y min:', ...
    'Style','text');
UIHandles.Inv_YMin = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'Style','edit');

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','max:', ...
    'Style','text');
UIHandles.Inv_YMax = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit2 stYEdit szXEdit szYEdit], ...
    'Style','edit');

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel3 stYLabel szXLabel3 szYEdit], ...
    'String','step:', ...
    'Style','text');
UIHandles.Inv_YStep = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit3 stYEdit szXEdit szYEdit], ...
    'Style','edit');

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel4 stYLabel szXLabel4 szYEdit], ...
    'String','cm', ...
    'Style','text');

stYEdit =  stYEdit - 2 - szYEdit;
stYLabel = stYEdit - 2;

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','Z min:', ...
    'Style','text');
UIHandles.Inv_ZMin = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'Style','edit');

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','max:', ...
    'Style','text');
UIHandles.Inv_ZMax = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit2 stYEdit szXEdit szYEdit], ...
    'Style','edit');

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel3 stYLabel szXLabel3 szYEdit], ...
    'String','step:', ...
    'Style','text');
UIHandles.Inv_ZStep = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit3 stYEdit szXEdit szYEdit], ...
    'Style','edit');

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel4 stYLabel szXLabel4 szYEdit], ...
    'String','cm', ...
    'Style','text');
