%UI_VISTECH
function [UIHandles, YEnd] = ui_vistech(hFig, UIHandles, XStart, szXFrame, YStart, szYEdit)

szYFrame = 5 * szYEdit + 16;
stYFrame = YStart - szYFrame - szYEdit;
YEnd = stYFrame;
stYEdit = YStart - szYEdit;
stYLabel = stYEdit - 2;

%%
%%  Visualization technique
%%
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[XStart stYFrame+szYFrame-5 szXFrame szYEdit], ...
    'String','Visualization Technique', ...
    'Style','text');

uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[XStart stYFrame szXFrame szYFrame], ...
    'Style','frame');

stXLabel1 = XStart + 2;
stYEdit = stYFrame + szYFrame - 4 - szYEdit;
stYLabel = stYEdit - 2;

szPlaneLbl = 47;
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szPlaneLbl szYEdit], ...
    'String','Image Plane:', ...
    'Style','text');
szPlaneRB = 40;
stPlaneRB = stXLabel1 + szPlaneLbl + szPlaneRB;
UIHandles.XPlane = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stPlaneRB stYEdit szPlaneRB szYEdit], ...
    'callback', 'rbVisPlane(''X'')', ...
    'String','X', ...
    'Style','radiobutton');
stPlaneRB = stPlaneRB + szPlaneRB;
UIHandles.YPlane = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stPlaneRB stYEdit szPlaneRB szYEdit], ...
    'callback', 'rbVisPlane(''Y'')', ...
    'String','Y', ...
    'Style','radiobutton');
stPlaneRB = stPlaneRB + szPlaneRB;
UIHandles.ZPlane = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stPlaneRB stYEdit szPlaneRB szYEdit], ...
    'callback', 'rbVisPlane(''Z'')', ...
    'String','Z', ...
    'Style','radiobutton');

stYEdit = stYEdit - szYEdit - 2;
stYLabel = stYEdit - 2;
szXZidxLbl = 50; 
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXZidxLbl szYEdit], ...
    'String','Plane Indices', ...
    'Style','text');
szXZidxEdt = 50;
stXZidxEdt = stXLabel1 + szXZidxLbl + 1;
UIHandles.PlaneIndices = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXZidxEdt stYEdit szXZidxEdt szYEdit], ...
    'Style','edit');

stXLayoutLbl = stXZidxEdt + szXZidxEdt + 5;
szXLayoutLbl = 60;
stXLayoutEdt = stXLayoutLbl + szXLayoutLbl + 1;
uicontrol('Parent',hFig, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLayoutLbl stYLabel szXLayoutLbl szYEdit], ...
    'String','Layout vector:', ...
    'Style','text');
szXLayoutEdt = 40;
UIHandles.LayoutVector = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXLayoutEdt stYEdit szXLayoutEdt szYEdit], ...
    'HorizontalAlignment','left', ...
    'Style','edit');


stYEdit = stYEdit - szYEdit - 2;
stYLabel = stYEdit - 2;
UIHandles.Image = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit 85 szYEdit], ...
    'callback', 'rbVisualize(''image'')', ...
    'String','Image', ...
    'Style','radiobutton');
stXContour = XStart + szXFrame/2-20;
szXContour = 63;
UIHandles.Contour = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXContour stYEdit szXContour szYEdit], ...
    'callback', 'rbVisualize(''contour'')', ...
    'String','Contour  lines:', ...
    'Style','radiobutton');

stNCLines = stXContour + szXContour + 1;
szNCLines = 60;
UIHandles.nCLines = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stNCLines stYEdit szNCLines szYEdit], ...
    'Style','edit');

stYEdit = stYEdit - szYEdit - 2;
stYLabel = stYEdit - 2;
stXCRange = XStart + szXFrame/2;
szXCRange = 80;
UIHandles.CMapBgyor = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit 85 szYEdit], ...
    'callback', 'rbColormap(''bgyor'')', ...
    'String','Blue - Red', ...
    'Style','radiobutton');

UIHandles.CRangeAuto = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXCRange stYEdit szXCRange szYEdit], ...
    'callback', 'rbColorRange(''auto'')', ...
    'String','Auto Color Range', ...
    'Style','radiobutton');

stYEdit = stYEdit - szYEdit - 2;
stYLabel = stYEdit - 2;
UIHandles.GreyScale = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit 85 szYEdit], ...
    'callback', 'rbColormap(''grey'')', ...
    'String','Grey Scale', ...
    'Style','radiobutton');
szXCRange = 40;
UIHandles.CRangeFixed = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'Position',[stXCRange stYEdit szXCRange szYEdit], ...
    'callback', 'rbColorRange(''fixed'')', ...
    'String','Fixed:', ...
    'Style','radiobutton');

stXCRFixedEdt = stXCRange + szXCRange + 1;
szXCRFixedEdt = 60;
UIHandles.CRangeVal = uicontrol('Parent',hFig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXCRFixedEdt stYEdit szXCRFixedEdt szYEdit], ...
    'HorizontalAlignment','left', ...
    'Style','edit');
