%SLABIMG        Imaging system for semi-infite slab DPDW problems.
%
%   slabimg(Mds)
%
%   Mds         OPTIONAL: The measurment data structure to use.
%
%
%   Calls: setall
%
%   Callbacks: rbBoundary, rbDataSource, rbRecon, doFwdMat, doMeasData, doRecon
%
%   Bugs: none known.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  $Author: rickg $
%
%  $Date: 2004/01/03 08:26:17 $
%
%  $Revision: 1.1.1.1 $
%
%  $Log: slabimg.m,v $
%  Revision 1.1.1.1  2004/01/03 08:26:17  rickg
%  Matlab Source
%
%  Revision 2.2  1999/02/05 20:50:25  rjg
%  Some GUI postional resizing.
%  Added entries for a block object
%  Noise value relabeling (hopefully clearer)
%  Vector norm relative noise
%
%  Revision 2.1  1998/08/07 21:30:10  rjg
%  Added the ability to slice in all three dimensions.
%  Plots now are place on a new figure until reset.
%
%  Revision 2.0  1998/08/05 16:06:56  rjg
%  Updated control dialog box.
%  Added depth and amplitude of sources.
%
%  Revision 1.5  1998/07/30 20:04:06  rjg
%  Removed SIdefines codes, uses string now.
%  UI for all three noise models
%  UI for TCG
%
%  Revision 1.4  1998/06/04 16:13:55  rjg
%  Changed label for SNR to dB from dB peak
%
%  Revision 1.3  1998/06/03 16:47:56  rjg
%  Uses SIdefines codes
%  Interface implementation for PMI execution
%  MTSVD interface
%  ART interface
%  restructured sphere object layout
%
%  Revision 1.2  1998/04/29 15:18:39  rjg
%  Added busy light.
%  
%  Created second column for reconstruction and visualization techniques.
%
%  Revision 1.1  1998/04/28 20:11:22  rjg
%  Initial revision
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function slabimg(ds)

%%
%%  Global UI layout parameters
%%
szXColumn = 228;
stYColumn = 500;
stXFrm = 4;
szXFrm = 220;
stCol2 = stXFrm + szXColumn;
stCol3 = stCol2 + szXColumn;

a = figure('Units','points', ...
    'Color', [0.7529 0.7529 0.7529], ...
    'Position',[3 24 2*szXColumn stYColumn]);

UI_Handles.FigControl = a;
set(a, 'MenuBar', 'none', 'NumberTitle', 'off', 'Name', 'DPDW Slab Imaging');

%%
%%  Busy light
%%
hBusyAx = axes('position', [0.95 0.01 0.03 0.03], ...
    'Color' ,'none', ...
    'visible', 'off');
hold on
UIHandles.hLight = plot(0.5, 0.5, 'og');

set(UIHandles.hLight, 'LineWidth', 8);


%%
%%  Computational volume
%%
szXEdit = 40;
szYEdit = 15;
szXLabel1 = 24;
stXLabel1 = stXFrm + 2;
stXEdit1 = stXLabel1 +szXLabel1+1;

szXLabel2 = 20;
stXLabel2 = stXEdit1 + szXEdit + 2;
stXEdit2 = stXLabel2 + szXLabel2 + 1;

szXLabel3 = 20;
stXLabel3 = stXEdit2 + szXEdit + 2;
stXEdit3 = stXLabel3 + szXLabel3 + 1;

szXLabel4 = 10;
stXLabel4 = stXEdit3 + szXEdit + 2;

stYEdit = stYColumn - szYEdit - 4;
szYFrmCmpVol = 3 * szYEdit + 4 + 8;
stYFrmCmpVol = stYEdit - szYFrmCmpVol;

stYLabel = stYEdit - 2;
szYFrmLabel = 11;

uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXFrm stYEdit szXFrm szYFrmLabel], ...
    'String','Computational Volume', ...
    'Style','text');

uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXFrm stYFrmCmpVol szXFrm szYFrmCmpVol], ...
    'Style','frame');

stYEdit =  stYEdit - 4 - szYEdit;
stYLabel = stYEdit - 2;

uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','X min:', ...
    'Style','text');
UIHandles.XMin = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'Style','edit');

uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','max:', ...
    'Style','text');
UIHandles.XMax = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit2 stYEdit szXEdit szYEdit], ...
    'Style','edit');

uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel3 stYLabel szXLabel3 szYEdit], ...
    'String','step:', ...
    'Style','text');
UIHandles.XStep = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit3 stYEdit szXEdit szYEdit], ...
    'Style','edit');

uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel4 stYLabel szXLabel4 szYEdit], ...
    'String','cm', ...
    'Style','text');

stYEdit =  stYEdit - 2 - szYEdit;
stYLabel = stYEdit - 2;

uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','Y min:', ...
    'Style','text');
UIHandles.YMin = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'Style','edit');

uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','max:', ...
    'Style','text');
UIHandles.YMax = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit2 stYEdit szXEdit szYEdit], ...
    'Style','edit');

uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel3 stYLabel szXLabel3 szYEdit], ...
    'String','step:', ...
    'Style','text');
UIHandles.YStep = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit3 stYEdit szXEdit szYEdit], ...
    'Style','edit');

uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel4 stYLabel szXLabel4 szYEdit], ...
    'String','cm', ...
    'Style','text');

stYEdit =  stYEdit - 2 - szYEdit;
stYLabel = stYEdit - 2;

uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','Z min:', ...
    'Style','text');
UIHandles.ZMin = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'Style','edit');

uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','max:', ...
    'Style','text');
UIHandles.ZMax = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit2 stYEdit szXEdit szYEdit], ...
    'Style','edit');

uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel3 stYLabel szXLabel3 szYEdit], ...
    'String','step:', ...
    'Style','text');
UIHandles.ZStep = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit3 stYEdit szXEdit szYEdit], ...
    'Style','edit');

uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel4 stYLabel szXLabel4 szYEdit], ...
    'String','cm', ...
    'Style','text');

%%
%%  Source & Detector Positions
%%
szYFrmSrcDet = 9 * szYEdit + 34;
stYFrmSrcDet = stYFrmCmpVol - szYFrmSrcDet - 6 - szYFrmLabel;

uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXFrm stYFrmSrcDet+szYFrmSrcDet szXFrm szYFrmLabel], ...
    'String','Source & Detector Data', ...
    'Style','text');

uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXFrm stYFrmSrcDet szXFrm szYFrmSrcDet], ...
    'Style','frame');

szXLabel1 = 55;
szXEdit = 120;
stXEdit1 = stXLabel1 + szXLabel1 + 1;
stXLabel2 = stXEdit1 + szXEdit + 2;
szXLabel2 = 30;

stYEdit = stYFrmSrcDet + szYFrmSrcDet - 4 - szYEdit;
stYLabel = stYEdit - 2;

%%
%%  Source X positions
%%
uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','Source Pos. X:', ...
    'Style','text');
UIHandles.SrcXPos = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'HorizontalAlignment','right', ...
    'Style','edit');
uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'HorizontalAlignment','left', ...
    'String','cm', ...
    'Style','text');

%%
%%  Source Y positions
%%
stYEdit = stYEdit - 2 - szYEdit;
stYLabel = stYEdit - 2;
uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','Y:', ...
    'Style','text');
UIHandles.SrcYPos = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'HorizontalAlignment','right', ...
    'Style','edit');

uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'HorizontalAlignment','left', ...
    'String','cm', ...
    'Style','text');

%%
%%  Source Z positions
%%
stYEdit = stYEdit - 2 - szYEdit;
stYLabel = stYEdit - 2;
uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','Z:', ...
    'Style','text');
UIHandles.SrcZPos = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'HorizontalAlignment','right', ...
    'Style','edit');

uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'HorizontalAlignment','left', ...
    'String','cm', ...
    'Style','text');

%%
%%  Source Amplitudes
%%
szXEditAmp = 60;
stXLabelAmp = stXEdit1 + szXEditAmp + 1;
szXLabelAmp = 100;
stYEdit = stYEdit - 2 - szYEdit;
stYLabel = stYEdit - 2;
uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','Amplitude:', ...
    'Style','text');
UIHandles.SrcAmp = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEditAmp szYEdit], ...
    'HorizontalAlignment','right', ...
    'Style','edit');
uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabelAmp stYLabel szXLabelAmp szYEdit], ...
    'HorizontalAlignment','left', ...
    'String','dB, per source plane', ...
    'Style','text');

%%
%%  Detector X positions
%%
stYEdit = stYEdit - 6 - szYEdit;
stYLabel = stYEdit - 2;
uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','Det. Pos. X:', ...
    'Style','text');
UIHandles.DetXPos = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'HorizontalAlignment','right', ...
    'Style','edit');
uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'HorizontalAlignment','left', ...
    'String','cm', ...
    'Style','text');

%%
%%  Detector Y positions
%%
stYEdit = stYEdit - 2 - szYEdit;
stYLabel = stYEdit - 2;
uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','Y:', ...
    'Style','text');
UIHandles.DetYPos = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'HorizontalAlignment','right', ...
    'Style','edit');
uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'HorizontalAlignment','left', ...
    'String','cm', ...
    'Style','text');

%%
%%  Detector Z positions
%%
stYEdit = stYEdit - 2 - szYEdit;
stYLabel = stYEdit - 2;
uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','Z:', ...
    'Style','text');
UIHandles.DetZPos = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'HorizontalAlignment','right', ...
    'Style','edit');
uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'HorizontalAlignment','left', ...
    'String','cm', ...
    'Style','text');

%%
%%  Sensor position error
%%
stYEdit = stYEdit - 6 - szYEdit;
stYLabel = stYEdit - 2;
uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','Position Error:', ...
    'Style','text');
UIHandles.SensorError = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.65 0.65 0.65], ...
    'enable', 'off',...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'Style','edit');
uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','cm std.', ...
    'Style','text');


stYEdit = stYEdit - 4 - szYEdit;
stYLabel = stYEdit - 2;
 uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','Mod. Freq.(s):', ...
    'Style','text');

UIHandles.ModFreq = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'Style','edit');
uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','MHz', ...
    'Style','text');


%%
%%  Medium parameters
%%
szYFrmMedium = 5 * szYEdit + 18;
stYFrmMedium = stYFrmSrcDet - 6 - szYFrmMedium - szYFrmLabel;

uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXFrm stYFrmMedium+szYFrmMedium szXFrm szYFrmLabel], ...
    'String','Medium Parameters', ...
    'Style','text');

uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXFrm stYFrmMedium szXFrm szYFrmMedium], ...
    'Style','frame');


szXLabel1 = 30; 
szXEdit = 100;
stXEdit1 = stXLabel1 + szXLabel1 + 1;
stXLabel2 = stXEdit1 + szXEdit + 1;
szXLabel2 = 60;

stYEdit = stYFrmMedium + szYFrmMedium - 4 - szYEdit;
stYLabel = stYEdit - 2;

%%
%%  Index of refraction
%%
uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','n:', ...
    'Style','text', ...
    'Tag','RefrIdx');
UIHandles.idxRefr = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'HorizontalAlignment','right', ...
    'Style','edit');

uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','refraction index', ...
    'Style','text');

%%
%%  Scattering mean cosine angle
%%
stYEdit = stYEdit - szYEdit - 2;
stYLabel = stYEdit - 2;
uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','g:', ...
    'Style','text');
UIHandles.g = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'Style','edit');
uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','mean cos angle', ...
    'Style','text');


%%
%%  Scattering coefficient
%%
stYEdit = stYEdit - szYEdit - 2;
stYLabel = stYEdit - 2;
uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','mu_s:', ...
    'Style','text');
UIHandles.Mu_s = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'Style','edit');
uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','cm^-1', ...
    'Style','text');


%%
%%  Absorption coefficient
%%
stYEdit = stYEdit - szYEdit - 2;
stYLabel = stYEdit - 2;
uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','mu_a:', ...
    'Style','text');
UIHandles.Mu_a = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'Style','edit');
uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','cm^-1', ...
    'Style','text');


%%
%%  Boundary condition implementation
%%
stYEdit = stYEdit - szYEdit - 6;
stYLabel = stYEdit - 2;
UIHandles.ExtrapBnd = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit 93.75 szYEdit], ...
    'callback', 'rbBoundary(''Extrapolated'')', ...
    'String','Extrapolated Boundary', ...
    'Style','radiobutton');

UIHandles.InfMedium = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXFrm+szXFrm/2 stYEdit 68.25 szYEdit], ...
    'callback', 'rbBoundary(''Infinite'')', ...
    'String','Infinite Medium', ...
    'Style','radiobutton');


%%
%%  2nd Column
%%
stXLabel1 = stCol2 + 2;

%%
%%  Measurement source
%%
szYFrmMeasure = 14 * szYEdit + 24;
stYEdit = stYColumn - szYEdit - 4;
stYFrmMeasure = stYEdit - szYFrmMeasure;


stXLabel2 = stCol2 + szXFrm/2;

szXLabel1 = 68;
stXEdit1 = stXLabel1 + szXLabel1 + 1;
szXEdit1 = 120;

uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stCol2 stYFrmMeasure+szYFrmMeasure szXFrm szYFrmLabel], ...
    'String','Measured Data Source', ...
    'Style','text');

uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stCol2 stYFrmMeasure szXFrm szYFrmMeasure], ...
    'Style','frame');


stYEdit = stYFrmMeasure + szYFrmMeasure - 4 - szYEdit;
stYLabel = stYEdit - 2;
UIHandles.MatlabVar = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit szXLabel1 szYEdit], ...
    'callback', 'rbDataSource(''Matlab Variable'')', ...
    'String','Matlab Variable', ...
    'Style','radiobutton');
UIHandles.MatlabVarName = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'HorizontalAlignment','left', ...
    'Style','edit');

stYEdit = stYEdit - 1 - szYEdit;
stYLabel = stYEdit - 2;
UIHandles.PMI = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit szXLabel1 szYEdit], ...
    'callback', 'rbDataSource(''PMI Script'')', ...
    'String','Exec PMI, File:', ...
    'Style','radiobutton');
UIHandles.PMIFileName = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'HorizontalAlignment','left', ...
    'Style','edit');

stYEdit = stYEdit - 1 - szYEdit;

UIHandles.Born1 = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit 65.25 szYEdit], ...
    'callback', 'rbDataSource(''Born-1'')', ...
    'String','Born-1', ...
    'Style','radiobutton');

UIHandles.Rytov = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stCol2+szXFrm/2-20 stYEdit 125 szYEdit], ...
    'callback', 'rbDataSource(''Rytov-1'')', ...
    'String','Rytov', ...
    'enable', 'off', ...
    'Style','radiobutton');

stYEdit = stYEdit -  szYEdit;
UIHandles.FDFD = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit 70 szYEdit], ...
    'callback', 'rbDataSource(''FDFD'')', ...
    'String','Finite Difference - Freq. Domain', ...
    'enable', 'off', ...
    'Style','radiobutton');

UIHandles.FiniteElem = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stCol2+szXFrm/2-20 stYEdit 125 szYEdit], ...
    'callback', 'rbDataSource(''FEM'')', ...
    'String','Finite Element', ...
    'enable', 'off', ...
    'Style','radiobutton');

uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stCol2+5 stYEdit-3.0 szXFrm-10 1.0], ...
    'Style','frame');

%%
%%  Noise level controls
%%
szXLabel1 = 70;
stXEdit1 = stXLabel1 + szXLabel1 + 1;
szXEdit1 = 25;
stXLabel2 = stXEdit1 + szXEdit1 + 1;
szXLabel2 = 120;
stYEdit = stYEdit - 6 - szYEdit;
stYLabel = stYEdit - 2;
UIHandles.SrcSNRflag = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit szXLabel1 szYEdit], ...
    'String','Source SNR:', ...
    'Style','checkbox');
UIHandles.SrcSNR = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'Style','edit');
uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','dB per det. rel. to total fluence', ...
    'Style','text');

stYEdit = stYEdit - 1 - szYEdit;
stYLabel = stYEdit - 2;
UIHandles.DetSNRflag = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit szXLabel1 szYEdit], ...
    'String','Detector SNR:', ...
    'Style','checkbox');
UIHandles.DetSNR = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'Style','edit');
uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','dB relative to peak scat. fluence', ...
    'Style','text');

stYEdit = stYEdit - 1 - szYEdit;
stYLabel = stYEdit - 2;
UIHandles.ScatSNRflag = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit szXLabel1 szYEdit], ...
    'String','Scattered SNR:', ...
    'Style','checkbox');
UIHandles.ScatSNR = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'Style','edit');
uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','dB per det. rel. to scat. fluence', ...
    'Style','text');

stYEdit = stYEdit - 1 - szYEdit;
stYLabel = stYEdit - 2;
UIHandles.VecNormSNRflag = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit szXLabel1 szYEdit], ...
    'String','Vec. norm SNR:', ...
    'Style','checkbox');
UIHandles.VecNormSNR = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'Style','edit');
uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','dB rel. to scat. vector norm', ...
    'Style','text');


%%
%%  Spherical object(s) function
%%
szXLabel1 = 35;
stXEdit1 = stXLabel1 + szXLabel1 + 1;
szXEdit1 = 100;
stXLabel2 = stXEdit1 + szXEdit1 + 2;
szXLabel2 = 28;
stXEdit2 = stXLabel2 + szXLabel2 + 1;
szXEdit2 = 50;
stXLabel3 = stXEdit2 + szXEdit2 + 2;

stYEdit = stYEdit - 2 - szYEdit;
stYLabel = stYEdit - 2;
uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','Sphere', ...
    'Style','text');

stYEdit = stYEdit - szYEdit;
stYLabel = stYEdit - 2;
uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','center(s):', ...
    'Style','text');

UIHandles.SphereCtr = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'Style','edit');

uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','radius:', ...
    'Style','text');

UIHandles.SphereRad = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit2 stYEdit szXEdit2 szYEdit], ...
    'Style','edit');

stYEdit = stYEdit - szYEdit;
stYLabel = stYEdit - 2;
szXLabel1 = 35;
stXEdit1 = stXLabel1 + szXLabel1 + 1;
szXEdit1 = 100;

uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','del mu_a:', ...
    'Style','text');

UIHandles.SphereDelta = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'Style','edit');

%%
%%  Block object function
%%
stYEdit = stYEdit - 2 - szYEdit;
stYLabel = stYEdit - 2;
uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','Block', ...
    'Style','text');

stYEdit = stYEdit - szYEdit;
stYLabel = stYEdit - 2;
uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','center(s):', ...
    'Style','text');

UIHandles.BlockCtr = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'Style','edit');

uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','lengths:', ...
    'Style','text');

UIHandles.BlockDims = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit2 stYEdit szXEdit2 szYEdit], ...
    'Style','edit');

stYEdit = stYEdit - szYEdit;
stYLabel = stYEdit - 2;
szXLabel1 = 35;
stXEdit1 = stXLabel1 + szXLabel1 + 1;
szXEdit1 = 100;

uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','del mu_a:', ...
    'Style','text');

UIHandles.BlockDelta = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'Style','edit');

%%
%%  3rd Column
%%
%stXLabel1 = stCol3 + 2;

%%
%%  Reconstruction algoirthm
%%

szYFrmRecon = 5 * szYEdit + 6 * 2;
%stYEdit = stYColumn - szYEdit - 4;
%stYFrmRecon = stYEdit - szYFrmRecon;
stYFrmRecon = stYFrmMeasure - szYFrmRecon - 4 - szYFrmLabel;
stYLabel = stYEdit - 2;
stXLabel2 = stCol2 + szXFrm/2;

uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stCol2 stYFrmRecon+szYFrmRecon szXFrm szYFrmLabel], ...
    'String','Reconstruction Algorithm', ...
    'Style','text');

uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stCol2 stYFrmRecon szXFrm szYFrmRecon], ...
    'Style','frame');

stYEdit = stYFrmRecon + szYFrmRecon - 2 - szYEdit;
UIHandles.BackProj = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit 85 szYEdit], ...
    'callback', 'rbRecon(''Back Projection'')', ...
    'String','Back Projection', ...
    'Style','radiobutton');


UIHandles.MinNorm = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel2 stYEdit 85 szYEdit], ...
    'callback', 'rbRecon(''Min. Norm'')', ...
    'String','Minimum Norm', ...
    'Style','radiobutton');


stYEdit = stYEdit - szYEdit - 2;
szXART = 65;
stNIter = stXLabel1 + szXART + 1;
szNIter = 35;

UIHandles.ART = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1  stYEdit szXART szYEdit], ...
    'callback', 'rbRecon(''ART'')', ...
    'String','ART iterations:', ...
    'Style','radiobutton');

UIHandles.ARTnIter = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stNIter stYEdit szNIter szYEdit], ...
    'Style','edit');


szXSIRT = 65;
stNIter = stXLabel2 + szXSIRT + 1;
UIHandles.SIRT = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel2 stYEdit szXSIRT szYEdit], ...
    'callback', 'rbRecon(''SIRT'')', ...
    'String','SIRT iterations:', ...
    'Style','radiobutton');

UIHandles.SIRTnIter = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stNIter stYEdit szNIter szYEdit], ...
    'Style','edit');


szXTSVD = 65;
stNSV = stXLabel1 + szXTSVD + 1;
stYEdit = stYEdit - szYEdit - 2;

UIHandles.TSVD = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit szXTSVD szYEdit], ...
    'callback', 'rbRecon(''TSVD'')', ...
    'String','TSVD # s.v.:', ...
    'Style','radiobutton');

UIHandles.TSVDnSV = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stNSV stYEdit szNIter szYEdit], ...
    'Style','edit');


stYEdit = stYEdit - szYEdit - 2;
stYLabel = stYEdit - 2;
UIHandles.MTSVD = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit szXTSVD szYEdit], ...
    'callback', 'rbRecon(''MTSVD'')', ...
    'String','MTSVD # s.v.:', ...
    'Style','radiobutton');

UIHandles.MTSVDnSV = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stNSV stYEdit szNIter szYEdit], ...
    'Style','edit');

stLabel1 = stNSV + szNIter + 1;
szLabel1 = 38;
uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stLabel1 stYLabel szLabel1 szYEdit], ...
    'String',',  lambda:', ...
    'Style','text');
stMTSVDL = stLabel1 + szLabel1 + 1;
szMTSVDL = 40;
UIHandles.MTSVDLambda = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stMTSVDL stYEdit szNIter szYEdit], ...
    'Style','edit');

szXTCG = 65;
stNTCG = stXLabel1 + szXTCG + 1;
stYEdit = stYEdit - szYEdit - 2;

UIHandles.TCG = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit szXTCG szYEdit], ...
    'callback', 'rbRecon(''TCG'')', ...
    'String','TCG iterations:', ...
    'Style','radiobutton');
UIHandles.TCGnIter = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stNTCG stYEdit szNIter szYEdit], ...
    'Style','edit');

%%
%%  Visualization technique
%%
szYFrmVisual = 5 * szYEdit + 16;
stYFrmVisual = stYFrmRecon - szYFrmVisual - 8 - szYFrmLabel;
uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','left', ...
    'Position',[stCol2 stYFrmVisual+szYFrmVisual szXFrm szYFrmLabel], ...
    'String','Visualization Technique', ...
    'Style','text');

uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stCol2 stYFrmVisual szXFrm szYFrmVisual], ...
    'Style','frame');

stYEdit = stYFrmVisual + szYFrmVisual - 4 - szYEdit;
stYLabel = stYEdit - 2;

szPlaneLbl = 47;
uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szPlaneLbl szYEdit], ...
    'String','Image Plane:', ...
    'Style','text');
szPlaneRB = 40;
stPlaneRB = stXLabel1 + szPlaneLbl + szPlaneRB;
UIHandles.XPlane = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stPlaneRB stYEdit szPlaneRB szYEdit], ...
    'callback', 'rbVisPlane(''X'')', ...
    'String','X', ...
    'Style','radiobutton');
stPlaneRB = stPlaneRB + szPlaneRB;
UIHandles.YPlane = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stPlaneRB stYEdit szPlaneRB szYEdit], ...
    'callback', 'rbVisPlane(''Y'')', ...
    'String','Y', ...
    'Style','radiobutton');
stPlaneRB = stPlaneRB + szPlaneRB;
UIHandles.ZPlane = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stPlaneRB stYEdit szPlaneRB szYEdit], ...
    'callback', 'rbVisPlane(''Z'')', ...
    'String','Z', ...
    'Style','radiobutton');

stYEdit = stYEdit - szYEdit - 2;
stYLabel = stYEdit - 2;
szXZidxLbl = 50; 
uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXZidxLbl szYEdit], ...
    'String','Plane Indices', ...
    'Style','text');
szXZidxEdt = 50;
stXZidxEdt = stXLabel1 + szXZidxLbl + 1;
UIHandles.PlaneIndices = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXZidxEdt stYEdit szXZidxEdt szYEdit], ...
    'Style','edit');

stXLayoutLbl = stXZidxEdt + szXZidxEdt + 5;
szXLayoutLbl = 60;
stXLayoutEdt = stXLayoutLbl + szXLayoutLbl + 1;
uicontrol('Parent',a, ...
    'Units','points', ...
    'HorizontalAlignment','right', ...
    'Position',[stXLayoutLbl stYLabel szXLayoutLbl szYEdit], ...
    'String','Layout vector:', ...
    'Style','text');
szXLayoutEdt = 40;
UIHandles.LayoutVector = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXLayoutEdt stYEdit szXLayoutEdt szYEdit], ...
    'HorizontalAlignment','left', ...
    'Style','edit');


stYEdit = stYEdit - szYEdit - 2;
stYLabel = stYEdit - 2;
UIHandles.Image = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit 85 szYEdit], ...
    'callback', 'rbVisualize(''image'')', ...
    'String','Image', ...
    'Style','radiobutton');
stXContour = stCol2 + szXFrm/2-20;
szXContour = 63;
UIHandles.Contour = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXContour stYEdit szXContour szYEdit], ...
    'callback', 'rbVisualize(''contour'')', ...
    'String','Contour  lines:', ...
    'Style','radiobutton');

stNCLines = stXContour + szXContour + 1;
szNCLines = 60;
UIHandles.nCLines = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stNCLines stYEdit szNCLines szYEdit], ...
    'Style','edit');

stYEdit = stYEdit - szYEdit - 2;
stYLabel = stYEdit - 2;
stXCRange = stCol2 + szXFrm/2;
szXCRange = 80;
UIHandles.CMapBgyor = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit 85 szYEdit], ...
    'callback', 'rbColormap(''bgyor'')', ...
    'String','Blue - Red', ...
    'Style','radiobutton');

UIHandles.CRangeAuto = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXCRange stYEdit szXCRange szYEdit], ...
    'callback', 'rbColorRange(''auto'')', ...
    'String','Auto Color Range', ...
    'Style','radiobutton');

stYEdit = stYEdit - szYEdit - 2;
stYLabel = stYEdit - 2;
UIHandles.GreyScale = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXLabel1 stYEdit 85 szYEdit], ...
    'callback', 'rbColormap(''grey'')', ...
    'String','Grey Scale', ...
    'Style','radiobutton');
szXCRange = 40;
UIHandles.CRangeFixed = uicontrol('Parent',a, ...
    'Units','points', ...
    'Position',[stXCRange stYEdit szXCRange szYEdit], ...
    'callback', 'rbColorRange(''fixed'')', ...
    'String','Fixed:', ...
    'Style','radiobutton');

stXCRFixedEdt = stXCRange + szXCRange + 1;
szXCRFixedEdt = 60;
UIHandles.CRangeVal = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXCRFixedEdt stYEdit szXCRFixedEdt szYEdit], ...
    'HorizontalAlignment','left', ...
    'Style','edit');

%%
%%  Calculation and control buttons
%%
uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'String', 'Calc Fwd', ...
    'callback', 'doFwdCalc', ...
    'Position',[5 5 50 17 ]', ...
    'Style','pushbutton');

uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'String', 'Meas. Data', ...
    'callback', 'doMeasData', ...
    'Position',[65 5 50 17 ]', ...
    'Style','pushbutton');

uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'String', 'Reconstruct', ...
    'callback', 'doRecon', ...
    'Position',[szXColumn+5 5 50 17 ]', ...
    'Style','pushbutton');

uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'String', 'Visualize', ...
    'callback', 'doVisualize', ...
    'Position',[szXColumn+65 5 50 17 ]', ...
    'Style','pushbutton');

uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'String', 'Reset Fig#', ...
    'callback', 'siCurrFigure=2;', ...
    'Position',[szXColumn+125 5 50 17 ]', ...
    'Style','pushbutton');

set(gcf, 'UserData', UIHandles);

if nargin > 0
    setall(ds,gcf);
end
orient tall