%DIV1D          1D central difference operator
%
%   D2 = div1d(nX, nY)
%
%   D2          The 1D sparse divergence operator.
%
%   nX, nY      The number of X and Y samples (this is the number of columns
%               and rows respectiveley of the 1D domain).
%
%
%   DIV1D generates a 1D divergence operator using a sparse matrix. 
%   The direction of increasing y is down the columns, this is
%   the same format generated by meshgrid.
%
%   Calls: none.
%
%   Bugs: none known.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  $Author: rickg $
%
%  $Date: 2004/01/03 08:25:08 $
%
%  $Revision: 1.1.1.1 $
%
%  $Log: div1d.m,v $
%  Revision 1.1.1.1  2004/01/03 08:25:08  rickg
%  Matlab Source
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function D1 = div1d(nX)

%%
%%  Compute the size of the sparse matrix
%%
M = (nX - 2);
N = nX;

D1 = sparse([1:M 1:M], [1:M (3:M+2)], ...
    [repmat(-1, 1, M) repmat(1, 1, M)], M, N);

