%DIV3D          3D divergence operator
%
%   D3 = di3d(nX, nY, nZ)
%
%   D3          The 3D sparse divergence operator.
%
%   nX, nY, nZ  The number of X,Y and Z samples (this is the number of columns
%               rows and planes respectiveley of the 3D domain).
%
%
%   DIV3D generates a 3D divergence operator using a sparse matrix.  The
%   assumes column major ordering in the data to be operated on.
%   Additionally, the direction of increasing y is down the columns, this is
%   the same format generated by meshgrid.
%
%   Calls: none.
%
%   Bugs: none known.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  $Author: rickg $
%
%  $Date: 2004/01/03 08:25:08 $
%
%  $Revision: 1.1.1.1 $
%
%  $Log: div3d.m,v $
%  Revision 1.1.1.1  2004/01/03 08:25:08  rickg
%  Matlab Source
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function D3 = div3d(nX, nY, nZ)

%%
%%  Compute the size of the sparse matrix
%%
M = (nX - 2) * (nY - 2) * (nZ - 2);
N = nX * nY * nZ;

%%
%%  Calculate the column major mapping of the vector to be operated on
%%
[l iY iZ] = meshgrid(2:(nX-1), 2:(nY-1), 2:(nZ-1));
l = (iZ(:) - 1) * (nY * nX) + (l(:) - 1) * nY + iY(:);

%%
%%  Fill in the non-zero entries
%%
D3 = sparse([1:M 1:M 1:M 1:M 1:M 1:M ], ...
    [l-1 l-nY l-(nX*nY) l+1 l+nY l+(nX*nY)], ...
    [repmat(-1, 1, 3*M) repmat(1, 1, 3*M)], M, N);
