#!/bin/sh
#
#  fairReference startup script

source ${PARTICLE_DIR}/particle.cfg

unset DISPLAY

echo -n "Starting fairReference_mce ..."
nice -n ${PARTICLE_NICE} fairReference_mce $@ >${1}.log 2>&1 &
echo "started as a background process."
