%peakInterpSO3 Second order volumetric peak interpolation

function [peak loc] = peakInterpSO3(locX, locY, locZ, vol)

if ndims(locX) < 3
  [locX locY locZ] = ndgrid(locX, locY, locZ);
end
% Fit a second order curve to the volume
nPoints = numel(locX)
coordMat = [locX(:).^2 locY(:).^2 locZ(:).^2 ...
  locX(:).*locY(:)  locX(:).*locZ(:)  locY(:).*locZ(:) ...
  locX(:)  locY(:) locZ(:) ones(nPoints, 1)];

a = coordMat \ vol(:)
cond(coordMat)

% Calculate the location of the gradient zero
coefMat = [ 2*a(1) a(4) a(5)
            2*a(2) a(4) a(6)
            2*a(3) a(5) a(6) ]
cond(coefMat)
loc = coefMat \ -[a(7) a(8) a(9)]';
peak = a(1) * loc(1)^2 ...
   + a(2) * loc(2)^2 ...
   + a(3) * loc(3)^2 ...
   + a(4) * loc(1) * loc(2) ...
   + a(5) * loc(1) * loc(3) ...
   + a(6) * loc(2) * loc(3) ...
   + a(7) * loc(1) ...
   + a(8) * loc(2) ...
   + a(9) * loc(3) ...
   + a(10);