%SLABIMG        Imaging system for semi-infite slab DPDW problems.
%
%   slabimg(Mds)
%
%   Mds         OPTIONAL: The measurment data structure to use.
%
%
%   Calls: setall
%
%   Callbacks: rbBoundary, rbDataSource, rbRecon, doFwdMat, doMeasData, doRecon
%
%   Bugs: none known.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  $Author: rickg $
%
%  $Date: 2004/01/03 08:26:00 $
%
%  $Revision: 1.1.1.1 $
%
%  $Log: slabimg.m,v $
%  Revision 1.1.1.1  2004/01/03 08:26:00  rickg
%  Matlab Source
%
%  Revision 1.5  1998/07/30 20:04:06  rjg
%  Removed SIdefines codes, uses string now.
%  UI for all three noise models
%  UI for TCG
%
%  Revision 1.4  1998/06/04 16:13:55  rjg
%  Changed label for SNR to dB from dB peak
%
%  Revision 1.3  1998/06/03 16:47:56  rjg
%  Uses SIdefines codes
%  Interface implementation for PMI execution
%  MTSVD interface
%  ART interface
%  restructured sphere object layout
%
%  Revision 1.2  1998/04/29 15:18:39  rjg
%  Added busy light.
%  
%  Created second column for reconstruction and visualization techniques.
%
%  Revision 1.1  1998/04/28 20:11:22  rjg
%  Initial revision
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function slabimg(ds)

szXColumn = 228;
stYColumn = 516;

a = figure('Units','points', ...
    'Color',[0.75 0.75 0.75], ...
    'Position',[3.75 25 2*szXColumn 520], ...
    'Tag','Fig1');
UI_Handles.FigControl = a;

%%
%%  Busy light
%%
hBusyAx = axes('position', [0.95 0.01 0.03 0.03], ...
    'Color' ,'none', ...
    'visible', 'off');
hold on
UIHandles.hLight = plot(0.5, 0.5, 'og');

set(UIHandles.hLight, 'LineWidth', 8);

stXFrm = 4;
szXFrm = 220;


%%
%%  Computational volume
%%
szXEdit = 40;
szYEdit = 15;
szXLabel1 = 24;
stXLabel1 = stXFrm + 2;
stXEdit1 = stXLabel1 +szXLabel1+1;

szXLabel2 = 20;
stXLabel2 = stXEdit1 + szXEdit + 2;
stXEdit2 = stXLabel2 + szXLabel2 + 1;

szXLabel3 = 20;
stXLabel3 = stXEdit2 + szXEdit + 2;
stXEdit3 = stXLabel3 + szXLabel3 + 1;

szXLabel4 = 10;
stXLabel4 = stXEdit3 + szXEdit + 2;

stYEdit = stYColumn - szYEdit - 4;
szYFrmCmpVol = 3 * szYEdit + 4 + 8;
stYFrmCmpVol = stYEdit - szYFrmCmpVol;

stYLabel = stYEdit - 2;
szYFrmLabel = 11;

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','left', ...
    'Position',[stXFrm stYEdit szXFrm szYFrmLabel], ...
    'String','Computational Volume', ...
    'Style','text', ...
    'Tag','ComputationalVolume');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXFrm stYFrmCmpVol szXFrm szYFrmCmpVol], ...
    'Style','frame', ...
    'Tag','CompVolFrame');

stYEdit =  stYEdit - 4 - szYEdit;
stYLabel = stYEdit - 2;

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','X min:', ...
    'Style','text', ...
    'Tag','XMinText');
UIHandles.XMin = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'Style','edit', ...
    'Tag','XMinEdit');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','max:', ...
    'Style','text', ...
    'Tag','XMaxText');
UIHandles.XMax = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit2 stYEdit szXEdit szYEdit], ...
    'Style','edit', ...
    'Tag','XMaxEdit');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel3 stYLabel szXLabel3 szYEdit], ...
    'String','step:', ...
    'Style','text', ...
    'Tag','XStepText');
UIHandles.XStep = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit3 stYEdit szXEdit szYEdit], ...
    'Style','edit', ...
    'Tag','XStepEdit');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel4 stYLabel szXLabel4 szYEdit], ...
    'String','cm', ...
    'Style','text', ...
    'Tag','XUnitsText');

stYEdit =  stYEdit - 2 - szYEdit;
stYLabel = stYEdit - 2;

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','Y min:', ...
    'Style','text', ...
    'Tag','YMinText');
UIHandles.YMin = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'Style','edit', ...
    'Tag','YMinEdit');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','max:', ...
    'Style','text', ...
    'Tag','YMaxText');
UIHandles.YMax = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit2 stYEdit szXEdit szYEdit], ...
    'Style','edit', ...
    'Tag','YMaxEdit');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel3 stYLabel szXLabel3 szYEdit], ...
    'String','step:', ...
    'Style','text', ...
    'Tag','YStepText');
UIHandles.YStep = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit3 stYEdit szXEdit szYEdit], ...
    'Style','edit', ...
    'Tag','YStepEdit');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel4 stYLabel szXLabel4 szYEdit], ...
    'String','cm', ...
    'Style','text', ...
    'Tag','YUnitsText');

stYEdit =  stYEdit - 2 - szYEdit;
stYLabel = stYEdit - 2;

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','Z min:', ...
    'Style','text', ...
    'Tag','ZMinText');
UIHandles.ZMin = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'Style','edit', ...
    'Tag','ZMinEdit');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','max:', ...
    'Style','text', ...
    'Tag','ZMaxText');
UIHandles.ZMax = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit2 stYEdit szXEdit szYEdit], ...
    'Style','edit', ...
    'Tag','ZMaxEdit');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel3 stYLabel szXLabel3 szYEdit], ...
    'String','step:', ...
    'Style','text', ...
    'Tag','ZStepText');
UIHandles.ZStep = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit3 stYEdit szXEdit szYEdit], ...
    'Style','edit', ...
    'Tag','ZStepEdit');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel4 stYLabel szXLabel4 szYEdit], ...
    'String','cm', ...
    'Style','text', ...
    'Tag','ZUnitsText');

%%
%%  Source & Detector Positions
%%
szYFrmSrcDet = 4 * szYEdit + 18;
stYFrmSrcDet = stYFrmCmpVol - szYFrmSrcDet - 8 - szYFrmLabel;

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','left', ...
    'Position',[stXFrm stYFrmSrcDet+szYFrmSrcDet szXFrm szYFrmLabel], ...
    'String','Source & Detector Data', ...
    'Style','text', ...
    'Tag','SourceDetectorText');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXFrm stYFrmSrcDet szXFrm szYFrmSrcDet], ...
    'Style','frame', ...
    'Tag','SrcDetFrame');

szXLabel1 = 62;
szXEdit = 60;
stYEdit = stYFrmSrcDet + szYFrmSrcDet - 4 - szYEdit;
stYLabel = stYEdit - 2;
stXEdit1 = stXLabel1 + szXLabel1 + 1;
stXLabel2 = stXEdit1 + szXEdit + 2;
szXLabel2 = 10;
stXEdit2 = stXLabel2 + szXLabel2 + 1;
stXLabel3 = stXEdit2 + szXEdit + 2;
szXLabel3 = 12;
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','Source Pos. X:', ...
    'Style','text', ...
    'Tag','SourcePosText');
UIHandles.SrcXPos = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'HorizontalAlignment','left', ...
    'Style','edit', ...
    'Tag','SourceXPosEdit');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','Y:', ...
    'Style','text', ...
    'Tag','SrcYPosText');
UIHandles.SrcYPos = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit2 stYEdit szXEdit szYEdit], ...
    'HorizontalAlignment','left', ...
    'Style','edit', ...
    'Tag','SourceYPosEdit');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel3 stYLabel szXLabel3 szYEdit], ...
    'HorizontalAlignment','left', ...
    'String','cm', ...
    'Style','text', ...
    'Tag','SourcePosUnits');

stYEdit = stYEdit - 2 - szYEdit;
stYLabel = stYEdit - 2;
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','Detector Pos.  X:', ...
    'Style','text', ...
    'Tag','DetPosText');
UIHandles.DetXPos = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'HorizontalAlignment','left', ...
    'Style','edit', ...
    'Tag','DetXPosEdit');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','Y:', ...
    'Style','text', ...
    'Tag','DetYPosText');
UIHandles.DetYPos = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit2 stYEdit szXEdit szYEdit], ...
    'HorizontalAlignment','left', ...
    'Style','edit', ...
    'Tag','DetYPosEdit');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel3 stYLabel szXLabel3 szYEdit], ...
    'String','cm', ...
    'Style','text', ...
    'Tag','DetPosUnits');

stYEdit = stYEdit - 4 - szYEdit;
stYLabel = stYEdit - 2;
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1+10 szYEdit], ...
    'String','Sensor Pos. Error:', ...
    'Style','text', ...
    'Tag','SensorPosLabel');
UIHandles.SensorError = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.65 0.65 0.65], ...
    'enable', 'off',...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1+10 stYEdit szXEdit szYEdit], ...
    'Style','edit', ...
    'Tag','SensorPosErr');
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2+10 stYLabel 45 szYEdit], ...
    'String','cm std.', ...
    'Style','text', ...
    'Tag','SensorPosUnits');

stYEdit = stYEdit - 4 - szYEdit;
stYLabel = stYEdit - 2;
szXFreqEdit = szXFrm * 0.56;
stXFreqUnits = stXEdit1+10+szXFreqEdit+1;
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1+8 szYEdit], ...
    'String','Modulation Freq.(s):', ...
    'Style','text', ...
    'Tag','SensorModLabel');
UIHandles.ModFreq = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1+8 stYEdit szXFreqEdit szYEdit], ...
    'Style','edit', ...
    'Tag','ModFreq');
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','left', ...
    'Position',[stXFreqUnits stYLabel 18 szYEdit], ...
    'String','MHz', ...
    'Style','text', ...
    'Tag','FreqUnits');


%%
%%  Medium parameters
%%
szYFrmMedium = 5 * szYEdit + 18;
stYFrmMedium = stYFrmSrcDet - 8 - szYFrmMedium - szYFrmLabel;

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','left', ...
    'Position',[stXFrm stYFrmMedium+szYFrmMedium szXFrm szYFrmLabel], ...
    'String','Medium Parameters', ...
    'Style','text', ...
    'Tag','MediumParameters');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXFrm stYFrmMedium szXFrm szYFrmMedium], ...
    'Style','frame', ...
    'Tag','MediumFrame');


szXLabel1 = 30; 
szXEdit = 100;
stXEdit1 = stXLabel1 + szXLabel1 + 1;
stXLabel2 = stXEdit1 + szXEdit + 1;
szXLabel2 = 60;

stYEdit = stYFrmMedium + szYFrmMedium - 4 - szYEdit;
stYLabel = stYEdit - 2;

%%
%%  Index of refraction
%%
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','n:', ...
    'Style','text', ...
    'Tag','RefrIdx');
UIHandles.idxRefr = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'HorizontalAlignment','right', ...
    'Style','edit', ...
    'Tag','RefrIdx');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','refraction index', ...
    'Style','text', ...
    'Tag','RefrIdxDesc');

%%
%%  Scattering mean cosine angle
%%
stYEdit = stYEdit - szYEdit - 2;
stYLabel = stYEdit - 2;
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','g:', ...
    'Style','text', ...
    'Tag','g');
UIHandles.g = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'Style','edit', ...
    'Tag','g');
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','mean cos angle', ...
    'Style','text', ...
    'Tag','g_desc');


%%
%%  Scattering coefficient
%%
stYEdit = stYEdit - szYEdit - 2;
stYLabel = stYEdit - 2;
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','mu_s:', ...
    'Style','text', ...
    'Tag','mu_s');
UIHandles.Mu_s = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'Style','edit', ...
    'Tag','mu_s');
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','cm^-1', ...
    'Style','text', ...
    'Tag','mu_s_units');


%%
%%  Absorption coefficient
%%
stYEdit = stYEdit - szYEdit - 2;
stYLabel = stYEdit - 2;
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'String','mu_a:', ...
    'Style','text', ...
    'Tag','mu_aText');
UIHandles.Mu_a = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit szYEdit], ...
    'Style','edit', ...
    'Tag','mu_a');
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','cm^-1', ...
    'Style','text', ...
    'Tag','mu_a_units');


%%
%%  Boundary condition implementation
%%
stYEdit = stYEdit - szYEdit - 6;
stYLabel = stYEdit - 2;
UIHandles.ExtrapBnd = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel1 stYEdit 93.75 szYEdit], ...
    'callback', 'rbBoundary(''Extrapolated'')', ...
    'String','Extrapolated Boundary', ...
    'Style','radiobutton', ...
    'Tag','ExtraplotedBC');

UIHandles.InfMedium = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXFrm+szXFrm/2 stYEdit 68.25 szYEdit], ...
    'callback', 'rbBoundary(''Infinite'')', ...
    'String','Infinite Medium', ...
    'Style','radiobutton', ...
    'Tag','InfMedium');


%%
%%  Measurement source
%%
szYFrmMeasure = 10 * szYEdit + 24;
stYFrmMeasure = stYFrmMedium - 8 - szYFrmMeasure - szYFrmLabel;

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','left', ...
    'Position',[stXFrm stYFrmMeasure+szYFrmMeasure szXFrm szYFrmLabel], ...
    'String','Measured Data Source', ...
    'Style','text', ...
    'Tag','MeasuredDataLabel');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXFrm stYFrmMeasure szXFrm szYFrmMeasure], ...
    'Style','frame', ...
    'Tag','MeasuredDataFrame');

szXLabel1 = 68;
stXEdit1 = stXLabel1 + szXLabel1 + 1;
szXEdit1 = 120;

stYEdit = stYFrmMeasure + szYFrmMeasure - 4 - szYEdit;
stYLabel = stYEdit - 2;
UIHandles.MatlabVar = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel1 stYEdit szXLabel1 szYEdit], ...
    'callback', 'rbDataSource(''Matlab Variable'')', ...
    'String','Matlab Variable', ...
    'Style','radiobutton', ...
    'Tag','MatlabVarData');
UIHandles.MatlabVarName = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'HorizontalAlignment','left', ...
    'Style','edit', ...
    'Tag','MatlabVarName');

stYEdit = stYEdit - 1 - szYEdit;
stYLabel = stYEdit - 2;
UIHandles.PMI = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel1 stYEdit szXLabel1 szYEdit], ...
    'callback', 'rbDataSource(''PMI Script'')', ...
    'String','Exec PMI, File:', ...
    'Style','radiobutton', ...
    'Tag','PMI_Run');
UIHandles.PMIFileName = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'HorizontalAlignment','left', ...
    'Style','edit', ...
    'Tag','PMIFileName');

stYEdit = stYEdit - 1 - szYEdit;

UIHandles.Born1 = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel1 stYEdit 65.25 szYEdit], ...
    'callback', 'rbDataSource(''Born-1'')', ...
    'String','Born-1', ...
    'Style','radiobutton', ...
    'Tag','Born1');

UIHandles.Rytov = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXFrm+szXFrm/2-20 stYEdit 125 szYEdit], ...
    'callback', 'rbDataSource(''Rytov-1'')', ...
    'String','Rytov', ...
    'enable', 'off', ...
    'Style','radiobutton', ...
    'Tag','Rytov');

stYEdit = stYEdit -  szYEdit;
UIHandles.FDFD = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...    
    'Position',[stXLabel1 stYEdit 70 szYEdit], ...
    'callback', 'rbDataSource(''FDFD'')', ...
    'String','Finite Difference - Freq. Domain', ...
    'enable', 'off', ...
    'Style','radiobutton', ...
    'Tag','FDFD');

UIHandles.FiniteElem = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...    
    'Position',[stXFrm+szXFrm/2-20 stYEdit 125 szYEdit], ...
    'callback', 'rbDataSource(''FEM'')', ...
    'String','Finite Element', ...
    'enable', 'off', ...
    'Style','radiobutton', ...
    'Tag','FE');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXFrm+5 stYEdit-3.0 szXFrm-10 1.0], ...
    'Style','frame', ...
    'Tag','Line');

%%
%%  Noise level controls
%%
szXLabel1 = 70;
stXEdit1 = stXLabel1 + szXLabel1 + 1;
szXEdit1 = 25;
stXLabel2 = stXEdit1 + szXEdit1 + 1;
szXLabel2 = 120;
stYEdit = stYEdit - 6 - szYEdit;
stYLabel = stYEdit - 2;
UIHandles.SrcSNRflag = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel1 stYEdit szXLabel1 szYEdit], ...
    'String','Source SNR:', ...
    'Style','checkbox', ...
    'Tag','SrcSNRLabel');
UIHandles.SrcSNR = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'Style','edit', ...
    'Tag','DetSNR');
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','dB per detector fluence', ...
    'Style','text', ...
    'Tag','SrcSNRUnits');

stYEdit = stYEdit - 1 - szYEdit;
stYLabel = stYEdit - 2;
UIHandles.DetSNRflag = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel1 stYEdit szXLabel1 szYEdit], ...
    'String','Detector SNR:', ...
    'Style','checkbox', ...
    'Tag','DetSNRLabel');
UIHandles.DetSNR = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'Style','edit', ...
    'Tag','DetSNR');
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','dB relative to peak fluence', ...
    'Style','text', ...
    'Tag','DetSNRUnits');

stYEdit = stYEdit - 1 - szYEdit;
stYLabel = stYEdit - 2;
UIHandles.ScatSNRflag = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel1 stYEdit szXLabel1 szYEdit], ...
    'String','Scattered SNR:', ...
    'Style','checkbox', ...
    'Tag','ScatSNRLabel');
UIHandles.ScatSNR = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','right', ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'Style','edit', ...
    'Tag','ScarSNR');
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','left', ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'String','dB per det. rel. to scat. fluence', ...
    'Style','text', ...
    'Tag','ScatSNRUnits');

%%
%%  Spherical object(s) function
%%
szXLabel1 = 35;
stXEdit1 = stXLabel1 + szXLabel1 + 1;
szXEdit1 = 100;
stXLabel2 = stXEdit1 + szXEdit1 + 2;
szXLabel2 = 28;
stXEdit2 = stXLabel2 + szXLabel2 + 1;
szXEdit2 = 50;
stXLabel3 = stXEdit2 + szXEdit2 + 2;

stYEdit = stYEdit - 2 - szYEdit;
stYLabel = stYEdit - 2;
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','Sphere', ...
    'Style','text', ...
    'Tag','SphereText');

stYEdit = stYEdit - szYEdit;
stYLabel = stYEdit - 2;
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','center(s):', ...
    'Style','text', ...
    'Tag','CenterText');

UIHandles.SphereCtr = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'Style','edit', ...
    'Tag','SphereCtr');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel2 stYLabel szXLabel2 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','radius:', ...
    'Style','text', ...
    'Tag','RadiusText');

UIHandles.SphereRad = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit2 stYEdit szXEdit2 szYEdit], ...
    'Style','edit', ...
    'Tag','SphereRadius');

stYEdit = stYEdit - szYEdit;
stYLabel = stYEdit - 2;
szXLabel1 = 35;
stXEdit1 = stXLabel1 + szXLabel1 + 1;
szXEdit1 = 100;

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel1 stYLabel szXLabel1 szYEdit], ...
    'HorizontalAlignment','right', ...
    'String','del mu_a:', ...
    'Style','text', ...
    'Tag','DeltaText');

UIHandles.SphereDelta = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXEdit1 stYEdit szXEdit1 szYEdit], ...
    'Style','edit', ...
    'Tag','SphereDelta');

%%
%%  Reconstruction algoirthm
%%
stCol2 = stXFrm + szXColumn;
stXLabel1 = stCol2 + 2;
stXLabel2 = stCol2 + szXFrm/2;

stYEdit = stYColumn - szYEdit - 4;
szYFrmRecon = 5 * szYEdit + 6 * 2;
stYFrmRecon = stYEdit - szYFrmRecon;

stYLabel = stYEdit - 2;

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','left', ...
    'Position',[stCol2 stYEdit szXFrm szYFrmLabel], ...
    'String','Reconstruction Algorithm', ...
    'Style','text', ...
    'Tag','ReconLabel');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stCol2 stYFrmRecon szXFrm szYFrmRecon], ...
    'Style','frame', ...
    'Tag','ReconFrame');

stYEdit = stYFrmRecon + szYFrmRecon - 2 - szYEdit;
UIHandles.BackProj = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel1 stYEdit 85 szYEdit], ...
    'callback', 'rbRecon(''Back Projection'')', ...
    'String','Back Projection', ...
    'Style','radiobutton', ...
    'Tag','BackProj');


UIHandles.MinNorm = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel2 stYEdit 85 szYEdit], ...
    'callback', 'rbRecon(''Min. Norm'')', ...
    'String','Minimum Norm', ...
    'Style','radiobutton', ...
    'Tag','MinNorm');


stYEdit = stYEdit - szYEdit - 2;
szXART = 65;
stNIter = stXLabel1 + szXART + 1;
szNIter = 35;

UIHandles.ART = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel1  stYEdit szXART szYEdit], ...
    'callback', 'rbRecon(''ART'')', ...
    'String','ART iterations:', ...
    'Style','radiobutton', ...
    'Tag','Art');

UIHandles.ARTnIter = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stNIter stYEdit szNIter szYEdit], ...
    'Style','edit', ...
    'Tag','NIterART');


szXSIRT = 65;
stNIter = stXLabel2 + szXSIRT + 1;
UIHandles.SIRT = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel2 stYEdit szXSIRT szYEdit], ...
    'callback', 'rbRecon(''SIRT'')', ...
    'String','SIRT iterations:', ...
    'Style','radiobutton', ...
    'Tag','Sirt');

UIHandles.SIRTnIter = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stNIter stYEdit szNIter szYEdit], ...
    'Style','edit', ...
    'Tag','NIterSIRT');



szXTSVD = 65;
stNSV = stXLabel1 + szXTSVD + 1;
stYEdit = stYEdit - szYEdit - 2;

UIHandles.TSVD = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel1 stYEdit szXTSVD szYEdit], ...
    'callback', 'rbRecon(''TSVD'')', ...
    'String','TSVD # s.v.:', ...
    'Style','radiobutton', ...
    'Tag','TSVD');

UIHandles.TSVDnSV = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stNSV stYEdit szNIter szYEdit], ...
    'Style','edit', ...
    'Tag','TSVDnSV');


stYEdit = stYEdit - szYEdit - 2;
stYLabel = stYEdit - 2;
UIHandles.MTSVD = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel1 stYEdit szXTSVD szYEdit], ...
    'callback', 'rbRecon(''MTSVD'')', ...
    'String','MTSVD # s.v.:', ...
    'Style','radiobutton', ...
    'Tag','TSVD');

UIHandles.MTSVDnSV = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stNSV stYEdit szNIter szYEdit], ...
    'Style','edit', ...
    'Tag','MTSVDnSV');

stLabel1 = stNSV + szNIter + 1;
szLabel1 = 38;
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','left', ...
    'Position',[stLabel1 stYLabel szLabel1 szYEdit], ...
    'String',',  lambda:', ...
    'Style','text', ...
    'Tag','MTSVDLambdaText');

stMTSVDL = stLabel1 + szLabel1 + 1;
szMTSVDL = 40;
UIHandles.MTSVDLambda = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stMTSVDL stYEdit szNIter szYEdit], ...
    'Style','edit', ...
    'Tag','MTSVDLambda');

szXTCG = 65;
stNTCG = stXLabel1 + szXTCG + 1;
stYEdit = stYEdit - szYEdit - 2;

UIHandles.TCG = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel1 stYEdit szXTCG szYEdit], ...
    'callback', 'rbRecon(''TCG'')', ...
    'String','TCG iterations:', ...
    'Style','radiobutton', ...
    'Tag','TCG');

UIHandles.TCGnIter = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stNTCG stYEdit szNIter szYEdit], ...
    'Style','edit', ...
    'Tag','TCGnIter');

%%
%%  Visualization technique
%%
szYFrmVisual = 5 * szYEdit + 12;
stYFrmVisual = stYFrmRecon - szYFrmVisual - 8 - szYFrmLabel;
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','left', ...
    'Position',[stCol2 stYFrmVisual+szYFrmVisual szXFrm szYFrmLabel], ...
    'String','Visualization Technique', ...
    'Style','text', ...
    'Tag','VisLabel');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stCol2 stYFrmVisual szXFrm szYFrmVisual], ...
    'Style','frame', ...
    'Tag','VisualFrame');

stYEdit = stYFrmVisual + szYFrmVisual - 4 - szYEdit;
UIHandles.Image = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel1 stYEdit 85 szYEdit], ...
    'callback', 'rbVisualize(''image'')', ...
    'String','Image', ...
    'Style','radiobutton', ...
    'Tag','Image');

stXContour = stCol2 + szXFrm/2-20;
szXContour = 63;
UIHandles.Contour = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXContour stYEdit szXContour szYEdit], ...
    'callback', 'rbVisualize(''contour'')', ...
    'String','Contour  lines:', ...
    'Style','radiobutton', ...
    'Tag','Contour');

stNCLines = stXContour + szXContour + 1;
szNCLines = 60;
UIHandles.nCLines = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stNCLines stYEdit szNCLines szYEdit], ...
    'Style','edit', ...
    'Tag','nCLines');


stYEdit = stYEdit - szYEdit - 2;
stYLabel = stYEdit - 2;
szXZidxLbl = 35; 
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','right', ...
    'Position',[stXLabel1 stYLabel szXZidxLbl szYEdit], ...
    'String','Z Indices', ...
    'Style','text', ...
    'Tag','ZIndicesText');
szXZidxEdt = 50;
stXZidxEdt = stXLabel1 + szXZidxLbl + 1;
UIHandles.ZIndices = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'Position',[stXZidxEdt stYEdit szXZidxEdt szYEdit], ...
    'Style','edit', ...
    'Tag','ZIndices');

stXLayoutLbl = stXZidxEdt + szXZidxEdt + 5;
szXLayoutLbl = 60;
stXLayoutEdt = stXLayoutLbl + szXLayoutLbl + 1;
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'HorizontalAlignment','right', ...
    'Position',[stXLayoutLbl stYLabel szXLayoutLbl szYEdit], ...
    'String','Layout vector:', ...
    'Style','text', ...
    'Tag','LayoutVecText');
szXLayoutEdt = 60;
UIHandles.LayoutVector = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXLayoutEdt stYEdit szXLayoutEdt szYEdit], ...
    'HorizontalAlignment','left', ...
    'Style','edit', ...
    'Tag','LayoutVector');

stYEdit = stYEdit - szYEdit - 2;
stYLabel = stYEdit - 2;
UIHandles.CMapBgyor = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel1 stYEdit 85 szYEdit], ...
    'callback', 'rbColormap(''bgyor'')', ...
    'String','Blue - Red', ...
    'Style','radiobutton', ...
    'Tag','CMapBgyor');

stXCRange = stCol2 + szXFrm/2;
szXCRange = 80;
UIHandles.CRangeAuto = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXCRange stYEdit szXCRange szYEdit], ...
    'callback', 'rbColorRange(''auto'')', ...
    'String','Auto Color Range', ...
    'Style','radiobutton', ...
    'Tag','CRangeAuto');

stYEdit = stYEdit - szYEdit - 2;
stYLabel = stYEdit - 2;
UIHandles.GreyScale = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXLabel1 stYEdit 85 szYEdit], ...
    'callback', 'rbColormap(''grey'')', ...
    'String','Grey Scale', ...
    'Style','radiobutton', ...
    'Tag','GreyScale');
szXCRange = 40;
UIHandles.CRangeFixed = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'Position',[stXCRange stYEdit szXCRange szYEdit], ...
    'callback', 'rbColorRange(''fixed'')', ...
    'String','Fixed:', ...
    'Style','radiobutton', ...
    'Tag','CRangeFixed');

stXCRFixedEdt = stXCRange + szXCRange + 1;
szXCRFixedEdt = 60;
UIHandles.CRangeVal = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[stXCRFixedEdt stYEdit szXCRFixedEdt szYEdit], ...
    'HorizontalAlignment','left', ...
    'Style','edit', ...
    'Tag','CRangeVal');

%%
%%  Calculation and control buttons
%%
b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'String', 'Calc Fwd', ...
    'callback', 'doFwdCalc', ...
    'Position',[5 5 50 17 ]', ...
    'Style','pushbutton', ...
    'Tag','FWDbtn');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'String', 'Meas. Data', ...
    'callback', 'doMeasData', ...
    'Position',[65 5 50 17 ]', ...
    'Style','pushbutton', ...
    'Tag','Measbtn');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'String', 'Reconstruct', ...
    'callback', 'doRecon', ...
    'Position',[szXColumn+5 5 50 17 ]', ...
    'Style','pushbutton', ...
    'Tag','Reconbtn');

b = uicontrol('Parent',a, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'String', 'Visualize', ...
    'callback', 'doVisualize', ...
    'Position',[szXColumn+65 5 50 17 ]', ...
    'Style','pushbutton', ...
    'Tag','VislualBtn');

set(gcf, 'UserData', UIHandles);

if nargin > 0
    setall(ds,gcf);
end
orient tall