indent = 4
margin = 160
short_to_long_function_def = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
normalize_line_endings = "windows"
join_lines_based_on_source = true
indent_submodule = true
